package com.lji.local.spring.dce.model;

import java.io.Serializable;
import java.util.Date;

public class DceFundMonthReturnKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundmonthreturn_temp.fund_temp_id
     *
     * @mbggenerated
     */
    private String fundTempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundmonthreturn_temp.months
     *
     * @mbggenerated
     */
    private Date months;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundmonthreturn_temp.fund_temp_id
     *
     * @return the value of ism_fundmonthreturn_temp.fund_temp_id
     *
     * @mbggenerated
     */
    public String getFundTempId() {
        return fundTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundmonthreturn_temp.fund_temp_id
     *
     * @param fundTempId the value for ism_fundmonthreturn_temp.fund_temp_id
     *
     * @mbggenerated
     */
    public void setFundTempId(String fundTempId) {
        this.fundTempId = fundTempId == null ? null : fundTempId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundmonthreturn_temp.months
     *
     * @return the value of ism_fundmonthreturn_temp.months
     *
     * @mbggenerated
     */
    public Date getMonths() {
        return months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundmonthreturn_temp.months
     *
     * @param months the value for ism_fundmonthreturn_temp.months
     *
     * @mbggenerated
     */
    public void setMonths(Date months) {
        this.months = months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DceFundMonthReturnKey other = (DceFundMonthReturnKey) that;
        return (this.getFundTempId() == null ? other.getFundTempId() == null : this.getFundTempId().equals(other.getFundTempId()))
            && (this.getMonths() == null ? other.getMonths() == null : this.getMonths().equals(other.getMonths()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFundTempId() == null) ? 0 : getFundTempId().hashCode());
        result = prime * result + ((getMonths() == null) ? 0 : getMonths().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fundTempId=").append(fundTempId);
        sb.append(", months=").append(months);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}