package com.lji.local.spring.dce.model;

import java.io.Serializable;

public class DceFundMonthRorKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_monthly_ror.year_ror
     *
     * @mbggenerated
     */
    private Integer yearRor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_monthly_ror.month_ror
     *
     * @mbggenerated
     */
    private Integer monthRor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_monthly_ror.fund_id
     *
     * @mbggenerated
     */
    private String fundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_monthly_ror.year_ror
     *
     * @return the value of ism_fund_monthly_ror.year_ror
     *
     * @mbggenerated
     */
    public Integer getYearRor() {
        return yearRor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_monthly_ror.year_ror
     *
     * @param yearRor the value for ism_fund_monthly_ror.year_ror
     *
     * @mbggenerated
     */
    public void setYearRor(Integer yearRor) {
        this.yearRor = yearRor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_monthly_ror.month_ror
     *
     * @return the value of ism_fund_monthly_ror.month_ror
     *
     * @mbggenerated
     */
    public Integer getMonthRor() {
        return monthRor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_monthly_ror.month_ror
     *
     * @param monthRor the value for ism_fund_monthly_ror.month_ror
     *
     * @mbggenerated
     */
    public void setMonthRor(Integer monthRor) {
        this.monthRor = monthRor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_monthly_ror.fund_id
     *
     * @return the value of ism_fund_monthly_ror.fund_id
     *
     * @mbggenerated
     */
    public String getFundId() {
        return fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_monthly_ror.fund_id
     *
     * @param fundId the value for ism_fund_monthly_ror.fund_id
     *
     * @mbggenerated
     */
    public void setFundId(String fundId) {
        this.fundId = fundId == null ? null : fundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DceFundMonthRorKey other = (DceFundMonthRorKey) that;
        return (this.getYearRor() == null ? other.getYearRor() == null : this.getYearRor().equals(other.getYearRor()))
            && (this.getMonthRor() == null ? other.getMonthRor() == null : this.getMonthRor().equals(other.getMonthRor()))
            && (this.getFundId() == null ? other.getFundId() == null : this.getFundId().equals(other.getFundId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getYearRor() == null) ? 0 : getYearRor().hashCode());
        result = prime * result + ((getMonthRor() == null) ? 0 : getMonthRor().hashCode());
        result = prime * result + ((getFundId() == null) ? 0 : getFundId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", yearRor=").append(yearRor);
        sb.append(", monthRor=").append(monthRor);
        sb.append(", fundId=").append(fundId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}