package com.lji.local.spring.dce.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DceFund implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_temp_id
     *
     * @mbggenerated
     */
    private String fundTempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_source_id
     *
     * @mbggenerated
     */
    private String fundSourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_name
     *
     * @mbggenerated
     */
    private String fundName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_simple_name
     *
     * @mbggenerated
     */
    private String fundSimpleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_real_name
     *
     * @mbggenerated
     */
    private String fundRealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.company_simple_name
     *
     * @mbggenerated
     */
    private String companySimpleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_run
     *
     * @mbggenerated
     */
    private String fundRun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_investment_strategy
     *
     * @mbggenerated
     */
    private String fundInvestmentStrategy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_assets
     *
     * @mbggenerated
     */
    private String fundAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_createtime
     *
     * @mbggenerated
     */
    private Date fundCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_closetime
     *
     * @mbggenerated
     */
    private Date fundClosetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_trust_company
     *
     * @mbggenerated
     */
    private String fundTrustCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_bank
     *
     * @mbggenerated
     */
    private String fundBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_subscription_nav
     *
     * @mbggenerated
     */
    private String fundSubscriptionNav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_manager_nav
     *
     * @mbggenerated
     */
    private String fundManagerNav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_redeem_nav
     *
     * @mbggenerated
     */
    private String fundRedeemNav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.iscompany
     *
     * @mbggenerated
     */
    private Integer iscompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_netdate
     *
     * @mbggenerated
     */
    private Date fundNetdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_net
     *
     * @mbggenerated
     */
    private BigDecimal fundNet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_upnet
     *
     * @mbggenerated
     */
    private BigDecimal fundUpnet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_no
     *
     * @mbggenerated
     */
    private String fundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_from
     *
     * @mbggenerated
     */
    private Integer fundFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.company_code
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.is_calover
     *
     * @mbggenerated
     */
    private Integer isCalover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.has_report
     *
     * @mbggenerated
     */
    private Integer hasReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.is_complex
     *
     * @mbggenerated
     */
    private Integer isComplex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.fund_investment_object
     *
     * @mbggenerated
     */
    private String fundInvestmentObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_temp.verify_type
     *
     * @mbggenerated
     */
    private Integer verifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_temp_id
     *
     * @return the value of ism_fund_temp.fund_temp_id
     *
     * @mbggenerated
     */
    public String getFundTempId() {
        return fundTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_temp_id
     *
     * @param fundTempId the value for ism_fund_temp.fund_temp_id
     *
     * @mbggenerated
     */
    public void setFundTempId(String fundTempId) {
        this.fundTempId = fundTempId == null ? null : fundTempId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_source_id
     *
     * @return the value of ism_fund_temp.fund_source_id
     *
     * @mbggenerated
     */
    public String getFundSourceId() {
        return fundSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_source_id
     *
     * @param fundSourceId the value for ism_fund_temp.fund_source_id
     *
     * @mbggenerated
     */
    public void setFundSourceId(String fundSourceId) {
        this.fundSourceId = fundSourceId == null ? null : fundSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_name
     *
     * @return the value of ism_fund_temp.fund_name
     *
     * @mbggenerated
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_name
     *
     * @param fundName the value for ism_fund_temp.fund_name
     *
     * @mbggenerated
     */
    public void setFundName(String fundName) {
        this.fundName = fundName == null ? null : fundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_simple_name
     *
     * @return the value of ism_fund_temp.fund_simple_name
     *
     * @mbggenerated
     */
    public String getFundSimpleName() {
        return fundSimpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_simple_name
     *
     * @param fundSimpleName the value for ism_fund_temp.fund_simple_name
     *
     * @mbggenerated
     */
    public void setFundSimpleName(String fundSimpleName) {
        this.fundSimpleName = fundSimpleName == null ? null : fundSimpleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_real_name
     *
     * @return the value of ism_fund_temp.fund_real_name
     *
     * @mbggenerated
     */
    public String getFundRealName() {
        return fundRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_real_name
     *
     * @param fundRealName the value for ism_fund_temp.fund_real_name
     *
     * @mbggenerated
     */
    public void setFundRealName(String fundRealName) {
        this.fundRealName = fundRealName == null ? null : fundRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.company_name
     *
     * @return the value of ism_fund_temp.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.company_name
     *
     * @param companyName the value for ism_fund_temp.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.company_simple_name
     *
     * @return the value of ism_fund_temp.company_simple_name
     *
     * @mbggenerated
     */
    public String getCompanySimpleName() {
        return companySimpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.company_simple_name
     *
     * @param companySimpleName the value for ism_fund_temp.company_simple_name
     *
     * @mbggenerated
     */
    public void setCompanySimpleName(String companySimpleName) {
        this.companySimpleName = companySimpleName == null ? null : companySimpleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_run
     *
     * @return the value of ism_fund_temp.fund_run
     *
     * @mbggenerated
     */
    public String getFundRun() {
        return fundRun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_run
     *
     * @param fundRun the value for ism_fund_temp.fund_run
     *
     * @mbggenerated
     */
    public void setFundRun(String fundRun) {
        this.fundRun = fundRun == null ? null : fundRun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_investment_strategy
     *
     * @return the value of ism_fund_temp.fund_investment_strategy
     *
     * @mbggenerated
     */
    public String getFundInvestmentStrategy() {
        return fundInvestmentStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_investment_strategy
     *
     * @param fundInvestmentStrategy the value for ism_fund_temp.fund_investment_strategy
     *
     * @mbggenerated
     */
    public void setFundInvestmentStrategy(String fundInvestmentStrategy) {
        this.fundInvestmentStrategy = fundInvestmentStrategy == null ? null : fundInvestmentStrategy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_assets
     *
     * @return the value of ism_fund_temp.fund_assets
     *
     * @mbggenerated
     */
    public String getFundAssets() {
        return fundAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_assets
     *
     * @param fundAssets the value for ism_fund_temp.fund_assets
     *
     * @mbggenerated
     */
    public void setFundAssets(String fundAssets) {
        this.fundAssets = fundAssets == null ? null : fundAssets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_createtime
     *
     * @return the value of ism_fund_temp.fund_createtime
     *
     * @mbggenerated
     */
    public Date getFundCreatetime() {
        return fundCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_createtime
     *
     * @param fundCreatetime the value for ism_fund_temp.fund_createtime
     *
     * @mbggenerated
     */
    public void setFundCreatetime(Date fundCreatetime) {
        this.fundCreatetime = fundCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_closetime
     *
     * @return the value of ism_fund_temp.fund_closetime
     *
     * @mbggenerated
     */
    public Date getFundClosetime() {
        return fundClosetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_closetime
     *
     * @param fundClosetime the value for ism_fund_temp.fund_closetime
     *
     * @mbggenerated
     */
    public void setFundClosetime(Date fundClosetime) {
        this.fundClosetime = fundClosetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_trust_company
     *
     * @return the value of ism_fund_temp.fund_trust_company
     *
     * @mbggenerated
     */
    public String getFundTrustCompany() {
        return fundTrustCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_trust_company
     *
     * @param fundTrustCompany the value for ism_fund_temp.fund_trust_company
     *
     * @mbggenerated
     */
    public void setFundTrustCompany(String fundTrustCompany) {
        this.fundTrustCompany = fundTrustCompany == null ? null : fundTrustCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_bank
     *
     * @return the value of ism_fund_temp.fund_bank
     *
     * @mbggenerated
     */
    public String getFundBank() {
        return fundBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_bank
     *
     * @param fundBank the value for ism_fund_temp.fund_bank
     *
     * @mbggenerated
     */
    public void setFundBank(String fundBank) {
        this.fundBank = fundBank == null ? null : fundBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_subscription_nav
     *
     * @return the value of ism_fund_temp.fund_subscription_nav
     *
     * @mbggenerated
     */
    public String getFundSubscriptionNav() {
        return fundSubscriptionNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_subscription_nav
     *
     * @param fundSubscriptionNav the value for ism_fund_temp.fund_subscription_nav
     *
     * @mbggenerated
     */
    public void setFundSubscriptionNav(String fundSubscriptionNav) {
        this.fundSubscriptionNav = fundSubscriptionNav == null ? null : fundSubscriptionNav.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_manager_nav
     *
     * @return the value of ism_fund_temp.fund_manager_nav
     *
     * @mbggenerated
     */
    public String getFundManagerNav() {
        return fundManagerNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_manager_nav
     *
     * @param fundManagerNav the value for ism_fund_temp.fund_manager_nav
     *
     * @mbggenerated
     */
    public void setFundManagerNav(String fundManagerNav) {
        this.fundManagerNav = fundManagerNav == null ? null : fundManagerNav.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_redeem_nav
     *
     * @return the value of ism_fund_temp.fund_redeem_nav
     *
     * @mbggenerated
     */
    public String getFundRedeemNav() {
        return fundRedeemNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_redeem_nav
     *
     * @param fundRedeemNav the value for ism_fund_temp.fund_redeem_nav
     *
     * @mbggenerated
     */
    public void setFundRedeemNav(String fundRedeemNav) {
        this.fundRedeemNav = fundRedeemNav == null ? null : fundRedeemNav.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.iscompany
     *
     * @return the value of ism_fund_temp.iscompany
     *
     * @mbggenerated
     */
    public Integer getIscompany() {
        return iscompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.iscompany
     *
     * @param iscompany the value for ism_fund_temp.iscompany
     *
     * @mbggenerated
     */
    public void setIscompany(Integer iscompany) {
        this.iscompany = iscompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_netdate
     *
     * @return the value of ism_fund_temp.fund_netdate
     *
     * @mbggenerated
     */
    public Date getFundNetdate() {
        return fundNetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_netdate
     *
     * @param fundNetdate the value for ism_fund_temp.fund_netdate
     *
     * @mbggenerated
     */
    public void setFundNetdate(Date fundNetdate) {
        this.fundNetdate = fundNetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_net
     *
     * @return the value of ism_fund_temp.fund_net
     *
     * @mbggenerated
     */
    public BigDecimal getFundNet() {
        return fundNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_net
     *
     * @param fundNet the value for ism_fund_temp.fund_net
     *
     * @mbggenerated
     */
    public void setFundNet(BigDecimal fundNet) {
        this.fundNet = fundNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_upnet
     *
     * @return the value of ism_fund_temp.fund_upnet
     *
     * @mbggenerated
     */
    public BigDecimal getFundUpnet() {
        return fundUpnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_upnet
     *
     * @param fundUpnet the value for ism_fund_temp.fund_upnet
     *
     * @mbggenerated
     */
    public void setFundUpnet(BigDecimal fundUpnet) {
        this.fundUpnet = fundUpnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_no
     *
     * @return the value of ism_fund_temp.fund_no
     *
     * @mbggenerated
     */
    public String getFundNo() {
        return fundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_no
     *
     * @param fundNo the value for ism_fund_temp.fund_no
     *
     * @mbggenerated
     */
    public void setFundNo(String fundNo) {
        this.fundNo = fundNo == null ? null : fundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_from
     *
     * @return the value of ism_fund_temp.fund_from
     *
     * @mbggenerated
     */
    public Integer getFundFrom() {
        return fundFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_from
     *
     * @param fundFrom the value for ism_fund_temp.fund_from
     *
     * @mbggenerated
     */
    public void setFundFrom(Integer fundFrom) {
        this.fundFrom = fundFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.create_date
     *
     * @return the value of ism_fund_temp.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.create_date
     *
     * @param createDate the value for ism_fund_temp.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.creator
     *
     * @return the value of ism_fund_temp.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.creator
     *
     * @param creator the value for ism_fund_temp.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.updatetime
     *
     * @return the value of ism_fund_temp.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.updatetime
     *
     * @param updatetime the value for ism_fund_temp.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.company_code
     *
     * @return the value of ism_fund_temp.company_code
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.company_code
     *
     * @param companyCode the value for ism_fund_temp.company_code
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.is_calover
     *
     * @return the value of ism_fund_temp.is_calover
     *
     * @mbggenerated
     */
    public Integer getIsCalover() {
        return isCalover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.is_calover
     *
     * @param isCalover the value for ism_fund_temp.is_calover
     *
     * @mbggenerated
     */
    public void setIsCalover(Integer isCalover) {
        this.isCalover = isCalover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.has_report
     *
     * @return the value of ism_fund_temp.has_report
     *
     * @mbggenerated
     */
    public Integer getHasReport() {
        return hasReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.has_report
     *
     * @param hasReport the value for ism_fund_temp.has_report
     *
     * @mbggenerated
     */
    public void setHasReport(Integer hasReport) {
        this.hasReport = hasReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.is_complex
     *
     * @return the value of ism_fund_temp.is_complex
     *
     * @mbggenerated
     */
    public Integer getIsComplex() {
        return isComplex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.is_complex
     *
     * @param isComplex the value for ism_fund_temp.is_complex
     *
     * @mbggenerated
     */
    public void setIsComplex(Integer isComplex) {
        this.isComplex = isComplex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.fund_investment_object
     *
     * @return the value of ism_fund_temp.fund_investment_object
     *
     * @mbggenerated
     */
    public String getFundInvestmentObject() {
        return fundInvestmentObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.fund_investment_object
     *
     * @param fundInvestmentObject the value for ism_fund_temp.fund_investment_object
     *
     * @mbggenerated
     */
    public void setFundInvestmentObject(String fundInvestmentObject) {
        this.fundInvestmentObject = fundInvestmentObject == null ? null : fundInvestmentObject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_temp.verify_type
     *
     * @return the value of ism_fund_temp.verify_type
     *
     * @mbggenerated
     */
    public Integer getVerifyType() {
        return verifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_temp.verify_type
     *
     * @param verifyType the value for ism_fund_temp.verify_type
     *
     * @mbggenerated
     */
    public void setVerifyType(Integer verifyType) {
        this.verifyType = verifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DceFund other = (DceFund) that;
        return (this.getFundTempId() == null ? other.getFundTempId() == null : this.getFundTempId().equals(other.getFundTempId()))
            && (this.getFundSourceId() == null ? other.getFundSourceId() == null : this.getFundSourceId().equals(other.getFundSourceId()))
            && (this.getFundName() == null ? other.getFundName() == null : this.getFundName().equals(other.getFundName()))
            && (this.getFundSimpleName() == null ? other.getFundSimpleName() == null : this.getFundSimpleName().equals(other.getFundSimpleName()))
            && (this.getFundRealName() == null ? other.getFundRealName() == null : this.getFundRealName().equals(other.getFundRealName()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getCompanySimpleName() == null ? other.getCompanySimpleName() == null : this.getCompanySimpleName().equals(other.getCompanySimpleName()))
            && (this.getFundRun() == null ? other.getFundRun() == null : this.getFundRun().equals(other.getFundRun()))
            && (this.getFundInvestmentStrategy() == null ? other.getFundInvestmentStrategy() == null : this.getFundInvestmentStrategy().equals(other.getFundInvestmentStrategy()))
            && (this.getFundAssets() == null ? other.getFundAssets() == null : this.getFundAssets().equals(other.getFundAssets()))
            && (this.getFundCreatetime() == null ? other.getFundCreatetime() == null : this.getFundCreatetime().equals(other.getFundCreatetime()))
            && (this.getFundClosetime() == null ? other.getFundClosetime() == null : this.getFundClosetime().equals(other.getFundClosetime()))
            && (this.getFundTrustCompany() == null ? other.getFundTrustCompany() == null : this.getFundTrustCompany().equals(other.getFundTrustCompany()))
            && (this.getFundBank() == null ? other.getFundBank() == null : this.getFundBank().equals(other.getFundBank()))
            && (this.getFundSubscriptionNav() == null ? other.getFundSubscriptionNav() == null : this.getFundSubscriptionNav().equals(other.getFundSubscriptionNav()))
            && (this.getFundManagerNav() == null ? other.getFundManagerNav() == null : this.getFundManagerNav().equals(other.getFundManagerNav()))
            && (this.getFundRedeemNav() == null ? other.getFundRedeemNav() == null : this.getFundRedeemNav().equals(other.getFundRedeemNav()))
            && (this.getIscompany() == null ? other.getIscompany() == null : this.getIscompany().equals(other.getIscompany()))
            && (this.getFundNetdate() == null ? other.getFundNetdate() == null : this.getFundNetdate().equals(other.getFundNetdate()))
            && (this.getFundNet() == null ? other.getFundNet() == null : this.getFundNet().equals(other.getFundNet()))
            && (this.getFundUpnet() == null ? other.getFundUpnet() == null : this.getFundUpnet().equals(other.getFundUpnet()))
            && (this.getFundNo() == null ? other.getFundNo() == null : this.getFundNo().equals(other.getFundNo()))
            && (this.getFundFrom() == null ? other.getFundFrom() == null : this.getFundFrom().equals(other.getFundFrom()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
            && (this.getCompanyCode() == null ? other.getCompanyCode() == null : this.getCompanyCode().equals(other.getCompanyCode()))
            && (this.getIsCalover() == null ? other.getIsCalover() == null : this.getIsCalover().equals(other.getIsCalover()))
            && (this.getHasReport() == null ? other.getHasReport() == null : this.getHasReport().equals(other.getHasReport()))
            && (this.getIsComplex() == null ? other.getIsComplex() == null : this.getIsComplex().equals(other.getIsComplex()))
            && (this.getFundInvestmentObject() == null ? other.getFundInvestmentObject() == null : this.getFundInvestmentObject().equals(other.getFundInvestmentObject()))
            && (this.getVerifyType() == null ? other.getVerifyType() == null : this.getVerifyType().equals(other.getVerifyType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFundTempId() == null) ? 0 : getFundTempId().hashCode());
        result = prime * result + ((getFundSourceId() == null) ? 0 : getFundSourceId().hashCode());
        result = prime * result + ((getFundName() == null) ? 0 : getFundName().hashCode());
        result = prime * result + ((getFundSimpleName() == null) ? 0 : getFundSimpleName().hashCode());
        result = prime * result + ((getFundRealName() == null) ? 0 : getFundRealName().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getCompanySimpleName() == null) ? 0 : getCompanySimpleName().hashCode());
        result = prime * result + ((getFundRun() == null) ? 0 : getFundRun().hashCode());
        result = prime * result + ((getFundInvestmentStrategy() == null) ? 0 : getFundInvestmentStrategy().hashCode());
        result = prime * result + ((getFundAssets() == null) ? 0 : getFundAssets().hashCode());
        result = prime * result + ((getFundCreatetime() == null) ? 0 : getFundCreatetime().hashCode());
        result = prime * result + ((getFundClosetime() == null) ? 0 : getFundClosetime().hashCode());
        result = prime * result + ((getFundTrustCompany() == null) ? 0 : getFundTrustCompany().hashCode());
        result = prime * result + ((getFundBank() == null) ? 0 : getFundBank().hashCode());
        result = prime * result + ((getFundSubscriptionNav() == null) ? 0 : getFundSubscriptionNav().hashCode());
        result = prime * result + ((getFundManagerNav() == null) ? 0 : getFundManagerNav().hashCode());
        result = prime * result + ((getFundRedeemNav() == null) ? 0 : getFundRedeemNav().hashCode());
        result = prime * result + ((getIscompany() == null) ? 0 : getIscompany().hashCode());
        result = prime * result + ((getFundNetdate() == null) ? 0 : getFundNetdate().hashCode());
        result = prime * result + ((getFundNet() == null) ? 0 : getFundNet().hashCode());
        result = prime * result + ((getFundUpnet() == null) ? 0 : getFundUpnet().hashCode());
        result = prime * result + ((getFundNo() == null) ? 0 : getFundNo().hashCode());
        result = prime * result + ((getFundFrom() == null) ? 0 : getFundFrom().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        result = prime * result + ((getCompanyCode() == null) ? 0 : getCompanyCode().hashCode());
        result = prime * result + ((getIsCalover() == null) ? 0 : getIsCalover().hashCode());
        result = prime * result + ((getHasReport() == null) ? 0 : getHasReport().hashCode());
        result = prime * result + ((getIsComplex() == null) ? 0 : getIsComplex().hashCode());
        result = prime * result + ((getFundInvestmentObject() == null) ? 0 : getFundInvestmentObject().hashCode());
        result = prime * result + ((getVerifyType() == null) ? 0 : getVerifyType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fundTempId=").append(fundTempId);
        sb.append(", fundSourceId=").append(fundSourceId);
        sb.append(", fundName=").append(fundName);
        sb.append(", fundSimpleName=").append(fundSimpleName);
        sb.append(", fundRealName=").append(fundRealName);
        sb.append(", companyName=").append(companyName);
        sb.append(", companySimpleName=").append(companySimpleName);
        sb.append(", fundRun=").append(fundRun);
        sb.append(", fundInvestmentStrategy=").append(fundInvestmentStrategy);
        sb.append(", fundAssets=").append(fundAssets);
        sb.append(", fundCreatetime=").append(fundCreatetime);
        sb.append(", fundClosetime=").append(fundClosetime);
        sb.append(", fundTrustCompany=").append(fundTrustCompany);
        sb.append(", fundBank=").append(fundBank);
        sb.append(", fundSubscriptionNav=").append(fundSubscriptionNav);
        sb.append(", fundManagerNav=").append(fundManagerNav);
        sb.append(", fundRedeemNav=").append(fundRedeemNav);
        sb.append(", iscompany=").append(iscompany);
        sb.append(", fundNetdate=").append(fundNetdate);
        sb.append(", fundNet=").append(fundNet);
        sb.append(", fundUpnet=").append(fundUpnet);
        sb.append(", fundNo=").append(fundNo);
        sb.append(", fundFrom=").append(fundFrom);
        sb.append(", createDate=").append(createDate);
        sb.append(", creator=").append(creator);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", companyCode=").append(companyCode);
        sb.append(", isCalover=").append(isCalover);
        sb.append(", hasReport=").append(hasReport);
        sb.append(", isComplex=").append(isComplex);
        sb.append(", fundInvestmentObject=").append(fundInvestmentObject);
        sb.append(", verifyType=").append(verifyType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}