package com.lji.local.spring.dce.model;

import java.io.Serializable;
import java.util.Date;

public class DceQuotationKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_quotation.quotation_id
     *
     * @mbggenerated
     */
    private String quotationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_quotation.quotation_type
     *
     * @mbggenerated
     */
    private Integer quotationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_quotation.creat_date
     *
     * @mbggenerated
     */
    private Date creatDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_quotation.quotation_id
     *
     * @return the value of ism_quotation.quotation_id
     *
     * @mbggenerated
     */
    public String getQuotationId() {
        return quotationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_quotation.quotation_id
     *
     * @param quotationId the value for ism_quotation.quotation_id
     *
     * @mbggenerated
     */
    public void setQuotationId(String quotationId) {
        this.quotationId = quotationId == null ? null : quotationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_quotation.quotation_type
     *
     * @return the value of ism_quotation.quotation_type
     *
     * @mbggenerated
     */
    public Integer getQuotationType() {
        return quotationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_quotation.quotation_type
     *
     * @param quotationType the value for ism_quotation.quotation_type
     *
     * @mbggenerated
     */
    public void setQuotationType(Integer quotationType) {
        this.quotationType = quotationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_quotation.creat_date
     *
     * @return the value of ism_quotation.creat_date
     *
     * @mbggenerated
     */
    public Date getCreatDate() {
        return creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_quotation.creat_date
     *
     * @param creatDate the value for ism_quotation.creat_date
     *
     * @mbggenerated
     */
    public void setCreatDate(Date creatDate) {
        this.creatDate = creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DceQuotationKey other = (DceQuotationKey) that;
        return (this.getQuotationId() == null ? other.getQuotationId() == null : this.getQuotationId().equals(other.getQuotationId()))
            && (this.getQuotationType() == null ? other.getQuotationType() == null : this.getQuotationType().equals(other.getQuotationType()))
            && (this.getCreatDate() == null ? other.getCreatDate() == null : this.getCreatDate().equals(other.getCreatDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getQuotationId() == null) ? 0 : getQuotationId().hashCode());
        result = prime * result + ((getQuotationType() == null) ? 0 : getQuotationType().hashCode());
        result = prime * result + ((getCreatDate() == null) ? 0 : getCreatDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", quotationId=").append(quotationId);
        sb.append(", quotationType=").append(quotationType);
        sb.append(", creatDate=").append(creatDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}