package com.lji.local.spring.ism.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class IsmAchievementsTemp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.achievements_id
     *
     * @mbggenerated
     */
    private String achievementsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.fund_temp_id
     *
     * @mbggenerated
     */
    private String fundTempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.profit
     *
     * @mbggenerated
     */
    private BigDecimal profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.years_profit
     *
     * @mbggenerated
     */
    private BigDecimal yearsProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.max_back_val
     *
     * @mbggenerated
     */
    private BigDecimal maxBackVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.every_years_winrate
     *
     * @mbggenerated
     */
    private BigDecimal everyYearsWinrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.sharp_ratio
     *
     * @mbggenerated
     */
    private BigDecimal sharpRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.atinuo_ratio
     *
     * @mbggenerated
     */
    private BigDecimal atinuoRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.treynor_ratio
     *
     * @mbggenerated
     */
    private BigDecimal treynorRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.section_type
     *
     * @mbggenerated
     */
    private Integer sectionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.lastor
     *
     * @mbggenerated
     */
    private String lastor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_achievements_temp.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.achievements_id
     *
     * @return the value of ism_achievements_temp.achievements_id
     *
     * @mbggenerated
     */
    public String getAchievementsId() {
        return achievementsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.achievements_id
     *
     * @param achievementsId the value for ism_achievements_temp.achievements_id
     *
     * @mbggenerated
     */
    public void setAchievementsId(String achievementsId) {
        this.achievementsId = achievementsId == null ? null : achievementsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.fund_temp_id
     *
     * @return the value of ism_achievements_temp.fund_temp_id
     *
     * @mbggenerated
     */
    public String getFundTempId() {
        return fundTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.fund_temp_id
     *
     * @param fundTempId the value for ism_achievements_temp.fund_temp_id
     *
     * @mbggenerated
     */
    public void setFundTempId(String fundTempId) {
        this.fundTempId = fundTempId == null ? null : fundTempId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.profit
     *
     * @return the value of ism_achievements_temp.profit
     *
     * @mbggenerated
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.profit
     *
     * @param profit the value for ism_achievements_temp.profit
     *
     * @mbggenerated
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.years_profit
     *
     * @return the value of ism_achievements_temp.years_profit
     *
     * @mbggenerated
     */
    public BigDecimal getYearsProfit() {
        return yearsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.years_profit
     *
     * @param yearsProfit the value for ism_achievements_temp.years_profit
     *
     * @mbggenerated
     */
    public void setYearsProfit(BigDecimal yearsProfit) {
        this.yearsProfit = yearsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.max_back_val
     *
     * @return the value of ism_achievements_temp.max_back_val
     *
     * @mbggenerated
     */
    public BigDecimal getMaxBackVal() {
        return maxBackVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.max_back_val
     *
     * @param maxBackVal the value for ism_achievements_temp.max_back_val
     *
     * @mbggenerated
     */
    public void setMaxBackVal(BigDecimal maxBackVal) {
        this.maxBackVal = maxBackVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.every_years_winrate
     *
     * @return the value of ism_achievements_temp.every_years_winrate
     *
     * @mbggenerated
     */
    public BigDecimal getEveryYearsWinrate() {
        return everyYearsWinrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.every_years_winrate
     *
     * @param everyYearsWinrate the value for ism_achievements_temp.every_years_winrate
     *
     * @mbggenerated
     */
    public void setEveryYearsWinrate(BigDecimal everyYearsWinrate) {
        this.everyYearsWinrate = everyYearsWinrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.sharp_ratio
     *
     * @return the value of ism_achievements_temp.sharp_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getSharpRatio() {
        return sharpRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.sharp_ratio
     *
     * @param sharpRatio the value for ism_achievements_temp.sharp_ratio
     *
     * @mbggenerated
     */
    public void setSharpRatio(BigDecimal sharpRatio) {
        this.sharpRatio = sharpRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.atinuo_ratio
     *
     * @return the value of ism_achievements_temp.atinuo_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getAtinuoRatio() {
        return atinuoRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.atinuo_ratio
     *
     * @param atinuoRatio the value for ism_achievements_temp.atinuo_ratio
     *
     * @mbggenerated
     */
    public void setAtinuoRatio(BigDecimal atinuoRatio) {
        this.atinuoRatio = atinuoRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.treynor_ratio
     *
     * @return the value of ism_achievements_temp.treynor_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getTreynorRatio() {
        return treynorRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.treynor_ratio
     *
     * @param treynorRatio the value for ism_achievements_temp.treynor_ratio
     *
     * @mbggenerated
     */
    public void setTreynorRatio(BigDecimal treynorRatio) {
        this.treynorRatio = treynorRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.section_type
     *
     * @return the value of ism_achievements_temp.section_type
     *
     * @mbggenerated
     */
    public Integer getSectionType() {
        return sectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.section_type
     *
     * @param sectionType the value for ism_achievements_temp.section_type
     *
     * @mbggenerated
     */
    public void setSectionType(Integer sectionType) {
        this.sectionType = sectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.last_update_time
     *
     * @return the value of ism_achievements_temp.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.last_update_time
     *
     * @param lastUpdateTime the value for ism_achievements_temp.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.lastor
     *
     * @return the value of ism_achievements_temp.lastor
     *
     * @mbggenerated
     */
    public String getLastor() {
        return lastor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.lastor
     *
     * @param lastor the value for ism_achievements_temp.lastor
     *
     * @mbggenerated
     */
    public void setLastor(String lastor) {
        this.lastor = lastor == null ? null : lastor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.create_date
     *
     * @return the value of ism_achievements_temp.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.create_date
     *
     * @param createDate the value for ism_achievements_temp.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_achievements_temp.creator
     *
     * @return the value of ism_achievements_temp.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_achievements_temp.creator
     *
     * @param creator the value for ism_achievements_temp.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IsmAchievementsTemp other = (IsmAchievementsTemp) that;
        return (this.getAchievementsId() == null ? other.getAchievementsId() == null : this.getAchievementsId().equals(other.getAchievementsId()))
            && (this.getFundTempId() == null ? other.getFundTempId() == null : this.getFundTempId().equals(other.getFundTempId()))
            && (this.getProfit() == null ? other.getProfit() == null : this.getProfit().equals(other.getProfit()))
            && (this.getYearsProfit() == null ? other.getYearsProfit() == null : this.getYearsProfit().equals(other.getYearsProfit()))
            && (this.getMaxBackVal() == null ? other.getMaxBackVal() == null : this.getMaxBackVal().equals(other.getMaxBackVal()))
            && (this.getEveryYearsWinrate() == null ? other.getEveryYearsWinrate() == null : this.getEveryYearsWinrate().equals(other.getEveryYearsWinrate()))
            && (this.getSharpRatio() == null ? other.getSharpRatio() == null : this.getSharpRatio().equals(other.getSharpRatio()))
            && (this.getAtinuoRatio() == null ? other.getAtinuoRatio() == null : this.getAtinuoRatio().equals(other.getAtinuoRatio()))
            && (this.getTreynorRatio() == null ? other.getTreynorRatio() == null : this.getTreynorRatio().equals(other.getTreynorRatio()))
            && (this.getSectionType() == null ? other.getSectionType() == null : this.getSectionType().equals(other.getSectionType()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastor() == null ? other.getLastor() == null : this.getLastor().equals(other.getLastor()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAchievementsId() == null) ? 0 : getAchievementsId().hashCode());
        result = prime * result + ((getFundTempId() == null) ? 0 : getFundTempId().hashCode());
        result = prime * result + ((getProfit() == null) ? 0 : getProfit().hashCode());
        result = prime * result + ((getYearsProfit() == null) ? 0 : getYearsProfit().hashCode());
        result = prime * result + ((getMaxBackVal() == null) ? 0 : getMaxBackVal().hashCode());
        result = prime * result + ((getEveryYearsWinrate() == null) ? 0 : getEveryYearsWinrate().hashCode());
        result = prime * result + ((getSharpRatio() == null) ? 0 : getSharpRatio().hashCode());
        result = prime * result + ((getAtinuoRatio() == null) ? 0 : getAtinuoRatio().hashCode());
        result = prime * result + ((getTreynorRatio() == null) ? 0 : getTreynorRatio().hashCode());
        result = prime * result + ((getSectionType() == null) ? 0 : getSectionType().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastor() == null) ? 0 : getLastor().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", achievementsId=").append(achievementsId);
        sb.append(", fundTempId=").append(fundTempId);
        sb.append(", profit=").append(profit);
        sb.append(", yearsProfit=").append(yearsProfit);
        sb.append(", maxBackVal=").append(maxBackVal);
        sb.append(", everyYearsWinrate=").append(everyYearsWinrate);
        sb.append(", sharpRatio=").append(sharpRatio);
        sb.append(", atinuoRatio=").append(atinuoRatio);
        sb.append(", treynorRatio=").append(treynorRatio);
        sb.append(", sectionType=").append(sectionType);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", lastor=").append(lastor);
        sb.append(", createDate=").append(createDate);
        sb.append(", creator=").append(creator);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}