package com.lji.local.spring.ism.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class IsmFundNetTemp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundnet_temp_log.fundnet_id
     *
     * @mbggenerated
     */
    private String fundnetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundnet_temp_log.fund_temp_id
     *
     * @mbggenerated
     */
    private String fundTempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundnet_temp_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundnet_temp_log.fund_net
     *
     * @mbggenerated
     */
    private BigDecimal fundNet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundnet_temp_log.fund_upnet
     *
     * @mbggenerated
     */
    private BigDecimal fundUpnet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundnet_temp_log.fund_source
     *
     * @mbggenerated
     */
    private Integer fundSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundnet_temp_log.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundnet_temp_log.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundnet_temp_log.MODIFIER
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundnet_temp_log.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundnet_temp_log.fundnet_id
     *
     * @return the value of ism_fundnet_temp_log.fundnet_id
     *
     * @mbggenerated
     */
    public String getFundnetId() {
        return fundnetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundnet_temp_log.fundnet_id
     *
     * @param fundnetId the value for ism_fundnet_temp_log.fundnet_id
     *
     * @mbggenerated
     */
    public void setFundnetId(String fundnetId) {
        this.fundnetId = fundnetId == null ? null : fundnetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundnet_temp_log.fund_temp_id
     *
     * @return the value of ism_fundnet_temp_log.fund_temp_id
     *
     * @mbggenerated
     */
    public String getFundTempId() {
        return fundTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundnet_temp_log.fund_temp_id
     *
     * @param fundTempId the value for ism_fundnet_temp_log.fund_temp_id
     *
     * @mbggenerated
     */
    public void setFundTempId(String fundTempId) {
        this.fundTempId = fundTempId == null ? null : fundTempId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundnet_temp_log.create_time
     *
     * @return the value of ism_fundnet_temp_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundnet_temp_log.create_time
     *
     * @param createTime the value for ism_fundnet_temp_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundnet_temp_log.fund_net
     *
     * @return the value of ism_fundnet_temp_log.fund_net
     *
     * @mbggenerated
     */
    public BigDecimal getFundNet() {
        return fundNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundnet_temp_log.fund_net
     *
     * @param fundNet the value for ism_fundnet_temp_log.fund_net
     *
     * @mbggenerated
     */
    public void setFundNet(BigDecimal fundNet) {
        this.fundNet = fundNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundnet_temp_log.fund_upnet
     *
     * @return the value of ism_fundnet_temp_log.fund_upnet
     *
     * @mbggenerated
     */
    public BigDecimal getFundUpnet() {
        return fundUpnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundnet_temp_log.fund_upnet
     *
     * @param fundUpnet the value for ism_fundnet_temp_log.fund_upnet
     *
     * @mbggenerated
     */
    public void setFundUpnet(BigDecimal fundUpnet) {
        this.fundUpnet = fundUpnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundnet_temp_log.fund_source
     *
     * @return the value of ism_fundnet_temp_log.fund_source
     *
     * @mbggenerated
     */
    public Integer getFundSource() {
        return fundSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundnet_temp_log.fund_source
     *
     * @param fundSource the value for ism_fundnet_temp_log.fund_source
     *
     * @mbggenerated
     */
    public void setFundSource(Integer fundSource) {
        this.fundSource = fundSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundnet_temp_log.creator
     *
     * @return the value of ism_fundnet_temp_log.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundnet_temp_log.creator
     *
     * @param creator the value for ism_fundnet_temp_log.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundnet_temp_log.modify_date
     *
     * @return the value of ism_fundnet_temp_log.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundnet_temp_log.modify_date
     *
     * @param modifyDate the value for ism_fundnet_temp_log.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundnet_temp_log.MODIFIER
     *
     * @return the value of ism_fundnet_temp_log.MODIFIER
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundnet_temp_log.MODIFIER
     *
     * @param modifier the value for ism_fundnet_temp_log.MODIFIER
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundnet_temp_log.update_time
     *
     * @return the value of ism_fundnet_temp_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundnet_temp_log.update_time
     *
     * @param updateTime the value for ism_fundnet_temp_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IsmFundNetTemp other = (IsmFundNetTemp) that;
        return (this.getFundnetId() == null ? other.getFundnetId() == null : this.getFundnetId().equals(other.getFundnetId()))
            && (this.getFundTempId() == null ? other.getFundTempId() == null : this.getFundTempId().equals(other.getFundTempId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getFundNet() == null ? other.getFundNet() == null : this.getFundNet().equals(other.getFundNet()))
            && (this.getFundUpnet() == null ? other.getFundUpnet() == null : this.getFundUpnet().equals(other.getFundUpnet()))
            && (this.getFundSource() == null ? other.getFundSource() == null : this.getFundSource().equals(other.getFundSource()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getModifyDate() == null ? other.getModifyDate() == null : this.getModifyDate().equals(other.getModifyDate()))
            && (this.getModifier() == null ? other.getModifier() == null : this.getModifier().equals(other.getModifier()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFundnetId() == null) ? 0 : getFundnetId().hashCode());
        result = prime * result + ((getFundTempId() == null) ? 0 : getFundTempId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getFundNet() == null) ? 0 : getFundNet().hashCode());
        result = prime * result + ((getFundUpnet() == null) ? 0 : getFundUpnet().hashCode());
        result = prime * result + ((getFundSource() == null) ? 0 : getFundSource().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getModifyDate() == null) ? 0 : getModifyDate().hashCode());
        result = prime * result + ((getModifier() == null) ? 0 : getModifier().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fundnetId=").append(fundnetId);
        sb.append(", fundTempId=").append(fundTempId);
        sb.append(", createTime=").append(createTime);
        sb.append(", fundNet=").append(fundNet);
        sb.append(", fundUpnet=").append(fundUpnet);
        sb.append(", fundSource=").append(fundSource);
        sb.append(", creator=").append(creator);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", modifier=").append(modifier);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}