package com.lji.local.spring.ism.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class IsmFund implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_id
     *
     * @mbggenerated
     */
    private String fundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.last_batch_id
     *
     * @mbggenerated
     */
    private String lastBatchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_name
     *
     * @mbggenerated
     */
    private String fundName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_pinyin_name
     *
     * @mbggenerated
     */
    private String fundPinyinName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_pinyin_simplename
     *
     * @mbggenerated
     */
    private String fundPinyinSimplename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_simple_name
     *
     * @mbggenerated
     */
    private String fundSimpleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_createtime
     *
     * @mbggenerated
     */
    private Date fundCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_opentime
     *
     * @mbggenerated
     */
    private String fundOpentime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_type
     *
     * @mbggenerated
     */
    private String fundType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_no
     *
     * @mbggenerated
     */
    private String fundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_structure
     *
     * @mbggenerated
     */
    private String fundStructure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_status
     *
     * @mbggenerated
     */
    private Integer fundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_net
     *
     * @mbggenerated
     */
    private BigDecimal fundNet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_netdate
     *
     * @mbggenerated
     */
    private Date fundNetdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_upnet
     *
     * @mbggenerated
     */
    private BigDecimal fundUpnet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_file_id
     *
     * @mbggenerated
     */
    private String fundFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_invest_nav
     *
     * @mbggenerated
     */
    private BigDecimal fundInvestNav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_add_nav
     *
     * @mbggenerated
     */
    private BigDecimal fundAddNav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_subscription_nav
     *
     * @mbggenerated
     */
    private String fundSubscriptionNav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_manager_nav
     *
     * @mbggenerated
     */
    private String fundManagerNav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_redeem_nav
     *
     * @mbggenerated
     */
    private String fundRedeemNav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_grade
     *
     * @mbggenerated
     */
    private Integer fundGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_from
     *
     * @mbggenerated
     */
    private Integer fundFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.creat_date
     *
     * @mbggenerated
     */
    private Date creatDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.delete_flag
     *
     * @mbggenerated
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.pv_num
     *
     * @mbggenerated
     */
    private Integer pvNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_logo_file_id
     *
     * @mbggenerated
     */
    private String fundLogoFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_years_profit
     *
     * @mbggenerated
     */
    private BigDecimal fundYearsProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.optional_num
     *
     * @mbggenerated
     */
    private Integer optionalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_closetime
     *
     * @mbggenerated
     */
    private Date fundClosetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_investment_object
     *
     * @mbggenerated
     */
    private String fundInvestmentObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_investment_strategy
     *
     * @mbggenerated
     */
    private String fundInvestmentStrategy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_trust_company
     *
     * @mbggenerated
     */
    private String fundTrustCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_bank
     *
     * @mbggenerated
     */
    private String fundBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_share
     *
     * @mbggenerated
     */
    private BigDecimal fundShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_assets
     *
     * @mbggenerated
     */
    private String fundAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_run
     *
     * @mbggenerated
     */
    private String fundRun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_idea
     *
     * @mbggenerated
     */
    private String fundIdea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_account_from
     *
     * @mbggenerated
     */
    private String fundAccountFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_share_class
     *
     * @mbggenerated
     */
    private String fundShareClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_principal_security
     *
     * @mbggenerated
     */
    private String fundPrincipalSecurity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_predate
     *
     * @mbggenerated
     */
    private Date fundPredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.isupresult
     *
     * @mbggenerated
     */
    private Integer isupresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_user_name
     *
     * @mbggenerated
     */
    private String fundUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_weight
     *
     * @mbggenerated
     */
    private Integer fundWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_title
     *
     * @mbggenerated
     */
    private String fundTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_profit_type
     *
     * @mbggenerated
     */
    private Integer fundProfitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_create_profit
     *
     * @mbggenerated
     */
    private BigDecimal fundCreateProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_sixmonths_profit
     *
     * @mbggenerated
     */
    private BigDecimal fundSixmonthsProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_threemonths_profit
     *
     * @mbggenerated
     */
    private BigDecimal fundThreemonthsProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_twoyears_profit
     *
     * @mbggenerated
     */
    private BigDecimal fundTwoyearsProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_threeyears_profit
     *
     * @mbggenerated
     */
    private BigDecimal fundThreeyearsProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_sinceyears_profit
     *
     * @mbggenerated
     */
    private BigDecimal fundSinceyearsProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_onemonths_profit
     *
     * @mbggenerated
     */
    private BigDecimal fundOnemonthsProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_tags
     *
     * @mbggenerated
     */
    private String fundTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_annex_file_id
     *
     * @mbggenerated
     */
    private String fundAnnexFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_recommend_text
     *
     * @mbggenerated
     */
    private String fundRecommendText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_quasiclose_time
     *
     * @mbggenerated
     */
    private String fundQuasicloseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_serial_id
     *
     * @mbggenerated
     */
    private Integer fundSerialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.fund_notype
     *
     * @mbggenerated
     */
    private Integer fundNotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.isreport
     *
     * @mbggenerated
     */
    private Integer isreport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.isfdsub
     *
     * @mbggenerated
     */
    private Integer isfdsub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund.his_batch_id
     *
     * @mbggenerated
     */
    private String hisBatchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_id
     *
     * @return the value of ism_fund.fund_id
     *
     * @mbggenerated
     */
    public String getFundId() {
        return fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_id
     *
     * @param fundId the value for ism_fund.fund_id
     *
     * @mbggenerated
     */
    public void setFundId(String fundId) {
        this.fundId = fundId == null ? null : fundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.last_batch_id
     *
     * @return the value of ism_fund.last_batch_id
     *
     * @mbggenerated
     */
    public String getLastBatchId() {
        return lastBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.last_batch_id
     *
     * @param lastBatchId the value for ism_fund.last_batch_id
     *
     * @mbggenerated
     */
    public void setLastBatchId(String lastBatchId) {
        this.lastBatchId = lastBatchId == null ? null : lastBatchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_name
     *
     * @return the value of ism_fund.fund_name
     *
     * @mbggenerated
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_name
     *
     * @param fundName the value for ism_fund.fund_name
     *
     * @mbggenerated
     */
    public void setFundName(String fundName) {
        this.fundName = fundName == null ? null : fundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_pinyin_name
     *
     * @return the value of ism_fund.fund_pinyin_name
     *
     * @mbggenerated
     */
    public String getFundPinyinName() {
        return fundPinyinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_pinyin_name
     *
     * @param fundPinyinName the value for ism_fund.fund_pinyin_name
     *
     * @mbggenerated
     */
    public void setFundPinyinName(String fundPinyinName) {
        this.fundPinyinName = fundPinyinName == null ? null : fundPinyinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_pinyin_simplename
     *
     * @return the value of ism_fund.fund_pinyin_simplename
     *
     * @mbggenerated
     */
    public String getFundPinyinSimplename() {
        return fundPinyinSimplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_pinyin_simplename
     *
     * @param fundPinyinSimplename the value for ism_fund.fund_pinyin_simplename
     *
     * @mbggenerated
     */
    public void setFundPinyinSimplename(String fundPinyinSimplename) {
        this.fundPinyinSimplename = fundPinyinSimplename == null ? null : fundPinyinSimplename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_simple_name
     *
     * @return the value of ism_fund.fund_simple_name
     *
     * @mbggenerated
     */
    public String getFundSimpleName() {
        return fundSimpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_simple_name
     *
     * @param fundSimpleName the value for ism_fund.fund_simple_name
     *
     * @mbggenerated
     */
    public void setFundSimpleName(String fundSimpleName) {
        this.fundSimpleName = fundSimpleName == null ? null : fundSimpleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_createtime
     *
     * @return the value of ism_fund.fund_createtime
     *
     * @mbggenerated
     */
    public Date getFundCreatetime() {
        return fundCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_createtime
     *
     * @param fundCreatetime the value for ism_fund.fund_createtime
     *
     * @mbggenerated
     */
    public void setFundCreatetime(Date fundCreatetime) {
        this.fundCreatetime = fundCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_opentime
     *
     * @return the value of ism_fund.fund_opentime
     *
     * @mbggenerated
     */
    public String getFundOpentime() {
        return fundOpentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_opentime
     *
     * @param fundOpentime the value for ism_fund.fund_opentime
     *
     * @mbggenerated
     */
    public void setFundOpentime(String fundOpentime) {
        this.fundOpentime = fundOpentime == null ? null : fundOpentime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_type
     *
     * @return the value of ism_fund.fund_type
     *
     * @mbggenerated
     */
    public String getFundType() {
        return fundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_type
     *
     * @param fundType the value for ism_fund.fund_type
     *
     * @mbggenerated
     */
    public void setFundType(String fundType) {
        this.fundType = fundType == null ? null : fundType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_no
     *
     * @return the value of ism_fund.fund_no
     *
     * @mbggenerated
     */
    public String getFundNo() {
        return fundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_no
     *
     * @param fundNo the value for ism_fund.fund_no
     *
     * @mbggenerated
     */
    public void setFundNo(String fundNo) {
        this.fundNo = fundNo == null ? null : fundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_structure
     *
     * @return the value of ism_fund.fund_structure
     *
     * @mbggenerated
     */
    public String getFundStructure() {
        return fundStructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_structure
     *
     * @param fundStructure the value for ism_fund.fund_structure
     *
     * @mbggenerated
     */
    public void setFundStructure(String fundStructure) {
        this.fundStructure = fundStructure == null ? null : fundStructure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_status
     *
     * @return the value of ism_fund.fund_status
     *
     * @mbggenerated
     */
    public Integer getFundStatus() {
        return fundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_status
     *
     * @param fundStatus the value for ism_fund.fund_status
     *
     * @mbggenerated
     */
    public void setFundStatus(Integer fundStatus) {
        this.fundStatus = fundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_net
     *
     * @return the value of ism_fund.fund_net
     *
     * @mbggenerated
     */
    public BigDecimal getFundNet() {
        return fundNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_net
     *
     * @param fundNet the value for ism_fund.fund_net
     *
     * @mbggenerated
     */
    public void setFundNet(BigDecimal fundNet) {
        this.fundNet = fundNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_netdate
     *
     * @return the value of ism_fund.fund_netdate
     *
     * @mbggenerated
     */
    public Date getFundNetdate() {
        return fundNetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_netdate
     *
     * @param fundNetdate the value for ism_fund.fund_netdate
     *
     * @mbggenerated
     */
    public void setFundNetdate(Date fundNetdate) {
        this.fundNetdate = fundNetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_upnet
     *
     * @return the value of ism_fund.fund_upnet
     *
     * @mbggenerated
     */
    public BigDecimal getFundUpnet() {
        return fundUpnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_upnet
     *
     * @param fundUpnet the value for ism_fund.fund_upnet
     *
     * @mbggenerated
     */
    public void setFundUpnet(BigDecimal fundUpnet) {
        this.fundUpnet = fundUpnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_file_id
     *
     * @return the value of ism_fund.fund_file_id
     *
     * @mbggenerated
     */
    public String getFundFileId() {
        return fundFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_file_id
     *
     * @param fundFileId the value for ism_fund.fund_file_id
     *
     * @mbggenerated
     */
    public void setFundFileId(String fundFileId) {
        this.fundFileId = fundFileId == null ? null : fundFileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_invest_nav
     *
     * @return the value of ism_fund.fund_invest_nav
     *
     * @mbggenerated
     */
    public BigDecimal getFundInvestNav() {
        return fundInvestNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_invest_nav
     *
     * @param fundInvestNav the value for ism_fund.fund_invest_nav
     *
     * @mbggenerated
     */
    public void setFundInvestNav(BigDecimal fundInvestNav) {
        this.fundInvestNav = fundInvestNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_add_nav
     *
     * @return the value of ism_fund.fund_add_nav
     *
     * @mbggenerated
     */
    public BigDecimal getFundAddNav() {
        return fundAddNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_add_nav
     *
     * @param fundAddNav the value for ism_fund.fund_add_nav
     *
     * @mbggenerated
     */
    public void setFundAddNav(BigDecimal fundAddNav) {
        this.fundAddNav = fundAddNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_subscription_nav
     *
     * @return the value of ism_fund.fund_subscription_nav
     *
     * @mbggenerated
     */
    public String getFundSubscriptionNav() {
        return fundSubscriptionNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_subscription_nav
     *
     * @param fundSubscriptionNav the value for ism_fund.fund_subscription_nav
     *
     * @mbggenerated
     */
    public void setFundSubscriptionNav(String fundSubscriptionNav) {
        this.fundSubscriptionNav = fundSubscriptionNav == null ? null : fundSubscriptionNav.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_manager_nav
     *
     * @return the value of ism_fund.fund_manager_nav
     *
     * @mbggenerated
     */
    public String getFundManagerNav() {
        return fundManagerNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_manager_nav
     *
     * @param fundManagerNav the value for ism_fund.fund_manager_nav
     *
     * @mbggenerated
     */
    public void setFundManagerNav(String fundManagerNav) {
        this.fundManagerNav = fundManagerNav == null ? null : fundManagerNav.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_redeem_nav
     *
     * @return the value of ism_fund.fund_redeem_nav
     *
     * @mbggenerated
     */
    public String getFundRedeemNav() {
        return fundRedeemNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_redeem_nav
     *
     * @param fundRedeemNav the value for ism_fund.fund_redeem_nav
     *
     * @mbggenerated
     */
    public void setFundRedeemNav(String fundRedeemNav) {
        this.fundRedeemNav = fundRedeemNav == null ? null : fundRedeemNav.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_grade
     *
     * @return the value of ism_fund.fund_grade
     *
     * @mbggenerated
     */
    public Integer getFundGrade() {
        return fundGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_grade
     *
     * @param fundGrade the value for ism_fund.fund_grade
     *
     * @mbggenerated
     */
    public void setFundGrade(Integer fundGrade) {
        this.fundGrade = fundGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_from
     *
     * @return the value of ism_fund.fund_from
     *
     * @mbggenerated
     */
    public Integer getFundFrom() {
        return fundFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_from
     *
     * @param fundFrom the value for ism_fund.fund_from
     *
     * @mbggenerated
     */
    public void setFundFrom(Integer fundFrom) {
        this.fundFrom = fundFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.creat_date
     *
     * @return the value of ism_fund.creat_date
     *
     * @mbggenerated
     */
    public Date getCreatDate() {
        return creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.creat_date
     *
     * @param creatDate the value for ism_fund.creat_date
     *
     * @mbggenerated
     */
    public void setCreatDate(Date creatDate) {
        this.creatDate = creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.creator
     *
     * @return the value of ism_fund.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.creator
     *
     * @param creator the value for ism_fund.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.modify_date
     *
     * @return the value of ism_fund.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.modify_date
     *
     * @param modifyDate the value for ism_fund.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.modifier
     *
     * @return the value of ism_fund.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.modifier
     *
     * @param modifier the value for ism_fund.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.delete_flag
     *
     * @return the value of ism_fund.delete_flag
     *
     * @mbggenerated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.delete_flag
     *
     * @param deleteFlag the value for ism_fund.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.pv_num
     *
     * @return the value of ism_fund.pv_num
     *
     * @mbggenerated
     */
    public Integer getPvNum() {
        return pvNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.pv_num
     *
     * @param pvNum the value for ism_fund.pv_num
     *
     * @mbggenerated
     */
    public void setPvNum(Integer pvNum) {
        this.pvNum = pvNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.weight
     *
     * @return the value of ism_fund.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.weight
     *
     * @param weight the value for ism_fund.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_logo_file_id
     *
     * @return the value of ism_fund.fund_logo_file_id
     *
     * @mbggenerated
     */
    public String getFundLogoFileId() {
        return fundLogoFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_logo_file_id
     *
     * @param fundLogoFileId the value for ism_fund.fund_logo_file_id
     *
     * @mbggenerated
     */
    public void setFundLogoFileId(String fundLogoFileId) {
        this.fundLogoFileId = fundLogoFileId == null ? null : fundLogoFileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_years_profit
     *
     * @return the value of ism_fund.fund_years_profit
     *
     * @mbggenerated
     */
    public BigDecimal getFundYearsProfit() {
        return fundYearsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_years_profit
     *
     * @param fundYearsProfit the value for ism_fund.fund_years_profit
     *
     * @mbggenerated
     */
    public void setFundYearsProfit(BigDecimal fundYearsProfit) {
        this.fundYearsProfit = fundYearsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.optional_num
     *
     * @return the value of ism_fund.optional_num
     *
     * @mbggenerated
     */
    public Integer getOptionalNum() {
        return optionalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.optional_num
     *
     * @param optionalNum the value for ism_fund.optional_num
     *
     * @mbggenerated
     */
    public void setOptionalNum(Integer optionalNum) {
        this.optionalNum = optionalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_closetime
     *
     * @return the value of ism_fund.fund_closetime
     *
     * @mbggenerated
     */
    public Date getFundClosetime() {
        return fundClosetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_closetime
     *
     * @param fundClosetime the value for ism_fund.fund_closetime
     *
     * @mbggenerated
     */
    public void setFundClosetime(Date fundClosetime) {
        this.fundClosetime = fundClosetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_investment_object
     *
     * @return the value of ism_fund.fund_investment_object
     *
     * @mbggenerated
     */
    public String getFundInvestmentObject() {
        return fundInvestmentObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_investment_object
     *
     * @param fundInvestmentObject the value for ism_fund.fund_investment_object
     *
     * @mbggenerated
     */
    public void setFundInvestmentObject(String fundInvestmentObject) {
        this.fundInvestmentObject = fundInvestmentObject == null ? null : fundInvestmentObject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_investment_strategy
     *
     * @return the value of ism_fund.fund_investment_strategy
     *
     * @mbggenerated
     */
    public String getFundInvestmentStrategy() {
        return fundInvestmentStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_investment_strategy
     *
     * @param fundInvestmentStrategy the value for ism_fund.fund_investment_strategy
     *
     * @mbggenerated
     */
    public void setFundInvestmentStrategy(String fundInvestmentStrategy) {
        this.fundInvestmentStrategy = fundInvestmentStrategy == null ? null : fundInvestmentStrategy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_trust_company
     *
     * @return the value of ism_fund.fund_trust_company
     *
     * @mbggenerated
     */
    public String getFundTrustCompany() {
        return fundTrustCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_trust_company
     *
     * @param fundTrustCompany the value for ism_fund.fund_trust_company
     *
     * @mbggenerated
     */
    public void setFundTrustCompany(String fundTrustCompany) {
        this.fundTrustCompany = fundTrustCompany == null ? null : fundTrustCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_bank
     *
     * @return the value of ism_fund.fund_bank
     *
     * @mbggenerated
     */
    public String getFundBank() {
        return fundBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_bank
     *
     * @param fundBank the value for ism_fund.fund_bank
     *
     * @mbggenerated
     */
    public void setFundBank(String fundBank) {
        this.fundBank = fundBank == null ? null : fundBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_share
     *
     * @return the value of ism_fund.fund_share
     *
     * @mbggenerated
     */
    public BigDecimal getFundShare() {
        return fundShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_share
     *
     * @param fundShare the value for ism_fund.fund_share
     *
     * @mbggenerated
     */
    public void setFundShare(BigDecimal fundShare) {
        this.fundShare = fundShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_assets
     *
     * @return the value of ism_fund.fund_assets
     *
     * @mbggenerated
     */
    public String getFundAssets() {
        return fundAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_assets
     *
     * @param fundAssets the value for ism_fund.fund_assets
     *
     * @mbggenerated
     */
    public void setFundAssets(String fundAssets) {
        this.fundAssets = fundAssets == null ? null : fundAssets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_run
     *
     * @return the value of ism_fund.fund_run
     *
     * @mbggenerated
     */
    public String getFundRun() {
        return fundRun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_run
     *
     * @param fundRun the value for ism_fund.fund_run
     *
     * @mbggenerated
     */
    public void setFundRun(String fundRun) {
        this.fundRun = fundRun == null ? null : fundRun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_idea
     *
     * @return the value of ism_fund.fund_idea
     *
     * @mbggenerated
     */
    public String getFundIdea() {
        return fundIdea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_idea
     *
     * @param fundIdea the value for ism_fund.fund_idea
     *
     * @mbggenerated
     */
    public void setFundIdea(String fundIdea) {
        this.fundIdea = fundIdea == null ? null : fundIdea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_account_from
     *
     * @return the value of ism_fund.fund_account_from
     *
     * @mbggenerated
     */
    public String getFundAccountFrom() {
        return fundAccountFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_account_from
     *
     * @param fundAccountFrom the value for ism_fund.fund_account_from
     *
     * @mbggenerated
     */
    public void setFundAccountFrom(String fundAccountFrom) {
        this.fundAccountFrom = fundAccountFrom == null ? null : fundAccountFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_share_class
     *
     * @return the value of ism_fund.fund_share_class
     *
     * @mbggenerated
     */
    public String getFundShareClass() {
        return fundShareClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_share_class
     *
     * @param fundShareClass the value for ism_fund.fund_share_class
     *
     * @mbggenerated
     */
    public void setFundShareClass(String fundShareClass) {
        this.fundShareClass = fundShareClass == null ? null : fundShareClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_principal_security
     *
     * @return the value of ism_fund.fund_principal_security
     *
     * @mbggenerated
     */
    public String getFundPrincipalSecurity() {
        return fundPrincipalSecurity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_principal_security
     *
     * @param fundPrincipalSecurity the value for ism_fund.fund_principal_security
     *
     * @mbggenerated
     */
    public void setFundPrincipalSecurity(String fundPrincipalSecurity) {
        this.fundPrincipalSecurity = fundPrincipalSecurity == null ? null : fundPrincipalSecurity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_predate
     *
     * @return the value of ism_fund.fund_predate
     *
     * @mbggenerated
     */
    public Date getFundPredate() {
        return fundPredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_predate
     *
     * @param fundPredate the value for ism_fund.fund_predate
     *
     * @mbggenerated
     */
    public void setFundPredate(Date fundPredate) {
        this.fundPredate = fundPredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.isupresult
     *
     * @return the value of ism_fund.isupresult
     *
     * @mbggenerated
     */
    public Integer getIsupresult() {
        return isupresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.isupresult
     *
     * @param isupresult the value for ism_fund.isupresult
     *
     * @mbggenerated
     */
    public void setIsupresult(Integer isupresult) {
        this.isupresult = isupresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_user_name
     *
     * @return the value of ism_fund.fund_user_name
     *
     * @mbggenerated
     */
    public String getFundUserName() {
        return fundUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_user_name
     *
     * @param fundUserName the value for ism_fund.fund_user_name
     *
     * @mbggenerated
     */
    public void setFundUserName(String fundUserName) {
        this.fundUserName = fundUserName == null ? null : fundUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_weight
     *
     * @return the value of ism_fund.fund_weight
     *
     * @mbggenerated
     */
    public Integer getFundWeight() {
        return fundWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_weight
     *
     * @param fundWeight the value for ism_fund.fund_weight
     *
     * @mbggenerated
     */
    public void setFundWeight(Integer fundWeight) {
        this.fundWeight = fundWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_title
     *
     * @return the value of ism_fund.fund_title
     *
     * @mbggenerated
     */
    public String getFundTitle() {
        return fundTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_title
     *
     * @param fundTitle the value for ism_fund.fund_title
     *
     * @mbggenerated
     */
    public void setFundTitle(String fundTitle) {
        this.fundTitle = fundTitle == null ? null : fundTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_profit_type
     *
     * @return the value of ism_fund.fund_profit_type
     *
     * @mbggenerated
     */
    public Integer getFundProfitType() {
        return fundProfitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_profit_type
     *
     * @param fundProfitType the value for ism_fund.fund_profit_type
     *
     * @mbggenerated
     */
    public void setFundProfitType(Integer fundProfitType) {
        this.fundProfitType = fundProfitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_create_profit
     *
     * @return the value of ism_fund.fund_create_profit
     *
     * @mbggenerated
     */
    public BigDecimal getFundCreateProfit() {
        return fundCreateProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_create_profit
     *
     * @param fundCreateProfit the value for ism_fund.fund_create_profit
     *
     * @mbggenerated
     */
    public void setFundCreateProfit(BigDecimal fundCreateProfit) {
        this.fundCreateProfit = fundCreateProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_sixmonths_profit
     *
     * @return the value of ism_fund.fund_sixmonths_profit
     *
     * @mbggenerated
     */
    public BigDecimal getFundSixmonthsProfit() {
        return fundSixmonthsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_sixmonths_profit
     *
     * @param fundSixmonthsProfit the value for ism_fund.fund_sixmonths_profit
     *
     * @mbggenerated
     */
    public void setFundSixmonthsProfit(BigDecimal fundSixmonthsProfit) {
        this.fundSixmonthsProfit = fundSixmonthsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_threemonths_profit
     *
     * @return the value of ism_fund.fund_threemonths_profit
     *
     * @mbggenerated
     */
    public BigDecimal getFundThreemonthsProfit() {
        return fundThreemonthsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_threemonths_profit
     *
     * @param fundThreemonthsProfit the value for ism_fund.fund_threemonths_profit
     *
     * @mbggenerated
     */
    public void setFundThreemonthsProfit(BigDecimal fundThreemonthsProfit) {
        this.fundThreemonthsProfit = fundThreemonthsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_twoyears_profit
     *
     * @return the value of ism_fund.fund_twoyears_profit
     *
     * @mbggenerated
     */
    public BigDecimal getFundTwoyearsProfit() {
        return fundTwoyearsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_twoyears_profit
     *
     * @param fundTwoyearsProfit the value for ism_fund.fund_twoyears_profit
     *
     * @mbggenerated
     */
    public void setFundTwoyearsProfit(BigDecimal fundTwoyearsProfit) {
        this.fundTwoyearsProfit = fundTwoyearsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_threeyears_profit
     *
     * @return the value of ism_fund.fund_threeyears_profit
     *
     * @mbggenerated
     */
    public BigDecimal getFundThreeyearsProfit() {
        return fundThreeyearsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_threeyears_profit
     *
     * @param fundThreeyearsProfit the value for ism_fund.fund_threeyears_profit
     *
     * @mbggenerated
     */
    public void setFundThreeyearsProfit(BigDecimal fundThreeyearsProfit) {
        this.fundThreeyearsProfit = fundThreeyearsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_sinceyears_profit
     *
     * @return the value of ism_fund.fund_sinceyears_profit
     *
     * @mbggenerated
     */
    public BigDecimal getFundSinceyearsProfit() {
        return fundSinceyearsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_sinceyears_profit
     *
     * @param fundSinceyearsProfit the value for ism_fund.fund_sinceyears_profit
     *
     * @mbggenerated
     */
    public void setFundSinceyearsProfit(BigDecimal fundSinceyearsProfit) {
        this.fundSinceyearsProfit = fundSinceyearsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_onemonths_profit
     *
     * @return the value of ism_fund.fund_onemonths_profit
     *
     * @mbggenerated
     */
    public BigDecimal getFundOnemonthsProfit() {
        return fundOnemonthsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_onemonths_profit
     *
     * @param fundOnemonthsProfit the value for ism_fund.fund_onemonths_profit
     *
     * @mbggenerated
     */
    public void setFundOnemonthsProfit(BigDecimal fundOnemonthsProfit) {
        this.fundOnemonthsProfit = fundOnemonthsProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_tags
     *
     * @return the value of ism_fund.fund_tags
     *
     * @mbggenerated
     */
    public String getFundTags() {
        return fundTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_tags
     *
     * @param fundTags the value for ism_fund.fund_tags
     *
     * @mbggenerated
     */
    public void setFundTags(String fundTags) {
        this.fundTags = fundTags == null ? null : fundTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_annex_file_id
     *
     * @return the value of ism_fund.fund_annex_file_id
     *
     * @mbggenerated
     */
    public String getFundAnnexFileId() {
        return fundAnnexFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_annex_file_id
     *
     * @param fundAnnexFileId the value for ism_fund.fund_annex_file_id
     *
     * @mbggenerated
     */
    public void setFundAnnexFileId(String fundAnnexFileId) {
        this.fundAnnexFileId = fundAnnexFileId == null ? null : fundAnnexFileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_recommend_text
     *
     * @return the value of ism_fund.fund_recommend_text
     *
     * @mbggenerated
     */
    public String getFundRecommendText() {
        return fundRecommendText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_recommend_text
     *
     * @param fundRecommendText the value for ism_fund.fund_recommend_text
     *
     * @mbggenerated
     */
    public void setFundRecommendText(String fundRecommendText) {
        this.fundRecommendText = fundRecommendText == null ? null : fundRecommendText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_quasiclose_time
     *
     * @return the value of ism_fund.fund_quasiclose_time
     *
     * @mbggenerated
     */
    public String getFundQuasicloseTime() {
        return fundQuasicloseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_quasiclose_time
     *
     * @param fundQuasicloseTime the value for ism_fund.fund_quasiclose_time
     *
     * @mbggenerated
     */
    public void setFundQuasicloseTime(String fundQuasicloseTime) {
        this.fundQuasicloseTime = fundQuasicloseTime == null ? null : fundQuasicloseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_serial_id
     *
     * @return the value of ism_fund.fund_serial_id
     *
     * @mbggenerated
     */
    public Integer getFundSerialId() {
        return fundSerialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_serial_id
     *
     * @param fundSerialId the value for ism_fund.fund_serial_id
     *
     * @mbggenerated
     */
    public void setFundSerialId(Integer fundSerialId) {
        this.fundSerialId = fundSerialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.fund_notype
     *
     * @return the value of ism_fund.fund_notype
     *
     * @mbggenerated
     */
    public Integer getFundNotype() {
        return fundNotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.fund_notype
     *
     * @param fundNotype the value for ism_fund.fund_notype
     *
     * @mbggenerated
     */
    public void setFundNotype(Integer fundNotype) {
        this.fundNotype = fundNotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.isreport
     *
     * @return the value of ism_fund.isreport
     *
     * @mbggenerated
     */
    public Integer getIsreport() {
        return isreport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.isreport
     *
     * @param isreport the value for ism_fund.isreport
     *
     * @mbggenerated
     */
    public void setIsreport(Integer isreport) {
        this.isreport = isreport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.isfdsub
     *
     * @return the value of ism_fund.isfdsub
     *
     * @mbggenerated
     */
    public Integer getIsfdsub() {
        return isfdsub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.isfdsub
     *
     * @param isfdsub the value for ism_fund.isfdsub
     *
     * @mbggenerated
     */
    public void setIsfdsub(Integer isfdsub) {
        this.isfdsub = isfdsub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund.his_batch_id
     *
     * @return the value of ism_fund.his_batch_id
     *
     * @mbggenerated
     */
    public String getHisBatchId() {
        return hisBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund.his_batch_id
     *
     * @param hisBatchId the value for ism_fund.his_batch_id
     *
     * @mbggenerated
     */
    public void setHisBatchId(String hisBatchId) {
        this.hisBatchId = hisBatchId == null ? null : hisBatchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IsmFund other = (IsmFund) that;
        return (this.getFundId() == null ? other.getFundId() == null : this.getFundId().equals(other.getFundId()))
            && (this.getLastBatchId() == null ? other.getLastBatchId() == null : this.getLastBatchId().equals(other.getLastBatchId()))
            && (this.getFundName() == null ? other.getFundName() == null : this.getFundName().equals(other.getFundName()))
            && (this.getFundPinyinName() == null ? other.getFundPinyinName() == null : this.getFundPinyinName().equals(other.getFundPinyinName()))
            && (this.getFundPinyinSimplename() == null ? other.getFundPinyinSimplename() == null : this.getFundPinyinSimplename().equals(other.getFundPinyinSimplename()))
            && (this.getFundSimpleName() == null ? other.getFundSimpleName() == null : this.getFundSimpleName().equals(other.getFundSimpleName()))
            && (this.getFundCreatetime() == null ? other.getFundCreatetime() == null : this.getFundCreatetime().equals(other.getFundCreatetime()))
            && (this.getFundOpentime() == null ? other.getFundOpentime() == null : this.getFundOpentime().equals(other.getFundOpentime()))
            && (this.getFundType() == null ? other.getFundType() == null : this.getFundType().equals(other.getFundType()))
            && (this.getFundNo() == null ? other.getFundNo() == null : this.getFundNo().equals(other.getFundNo()))
            && (this.getFundStructure() == null ? other.getFundStructure() == null : this.getFundStructure().equals(other.getFundStructure()))
            && (this.getFundStatus() == null ? other.getFundStatus() == null : this.getFundStatus().equals(other.getFundStatus()))
            && (this.getFundNet() == null ? other.getFundNet() == null : this.getFundNet().equals(other.getFundNet()))
            && (this.getFundNetdate() == null ? other.getFundNetdate() == null : this.getFundNetdate().equals(other.getFundNetdate()))
            && (this.getFundUpnet() == null ? other.getFundUpnet() == null : this.getFundUpnet().equals(other.getFundUpnet()))
            && (this.getFundFileId() == null ? other.getFundFileId() == null : this.getFundFileId().equals(other.getFundFileId()))
            && (this.getFundInvestNav() == null ? other.getFundInvestNav() == null : this.getFundInvestNav().equals(other.getFundInvestNav()))
            && (this.getFundAddNav() == null ? other.getFundAddNav() == null : this.getFundAddNav().equals(other.getFundAddNav()))
            && (this.getFundSubscriptionNav() == null ? other.getFundSubscriptionNav() == null : this.getFundSubscriptionNav().equals(other.getFundSubscriptionNav()))
            && (this.getFundManagerNav() == null ? other.getFundManagerNav() == null : this.getFundManagerNav().equals(other.getFundManagerNav()))
            && (this.getFundRedeemNav() == null ? other.getFundRedeemNav() == null : this.getFundRedeemNav().equals(other.getFundRedeemNav()))
            && (this.getFundGrade() == null ? other.getFundGrade() == null : this.getFundGrade().equals(other.getFundGrade()))
            && (this.getFundFrom() == null ? other.getFundFrom() == null : this.getFundFrom().equals(other.getFundFrom()))
            && (this.getCreatDate() == null ? other.getCreatDate() == null : this.getCreatDate().equals(other.getCreatDate()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getModifyDate() == null ? other.getModifyDate() == null : this.getModifyDate().equals(other.getModifyDate()))
            && (this.getModifier() == null ? other.getModifier() == null : this.getModifier().equals(other.getModifier()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getPvNum() == null ? other.getPvNum() == null : this.getPvNum().equals(other.getPvNum()))
            && (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
            && (this.getFundLogoFileId() == null ? other.getFundLogoFileId() == null : this.getFundLogoFileId().equals(other.getFundLogoFileId()))
            && (this.getFundYearsProfit() == null ? other.getFundYearsProfit() == null : this.getFundYearsProfit().equals(other.getFundYearsProfit()))
            && (this.getOptionalNum() == null ? other.getOptionalNum() == null : this.getOptionalNum().equals(other.getOptionalNum()))
            && (this.getFundClosetime() == null ? other.getFundClosetime() == null : this.getFundClosetime().equals(other.getFundClosetime()))
            && (this.getFundInvestmentObject() == null ? other.getFundInvestmentObject() == null : this.getFundInvestmentObject().equals(other.getFundInvestmentObject()))
            && (this.getFundInvestmentStrategy() == null ? other.getFundInvestmentStrategy() == null : this.getFundInvestmentStrategy().equals(other.getFundInvestmentStrategy()))
            && (this.getFundTrustCompany() == null ? other.getFundTrustCompany() == null : this.getFundTrustCompany().equals(other.getFundTrustCompany()))
            && (this.getFundBank() == null ? other.getFundBank() == null : this.getFundBank().equals(other.getFundBank()))
            && (this.getFundShare() == null ? other.getFundShare() == null : this.getFundShare().equals(other.getFundShare()))
            && (this.getFundAssets() == null ? other.getFundAssets() == null : this.getFundAssets().equals(other.getFundAssets()))
            && (this.getFundRun() == null ? other.getFundRun() == null : this.getFundRun().equals(other.getFundRun()))
            && (this.getFundIdea() == null ? other.getFundIdea() == null : this.getFundIdea().equals(other.getFundIdea()))
            && (this.getFundAccountFrom() == null ? other.getFundAccountFrom() == null : this.getFundAccountFrom().equals(other.getFundAccountFrom()))
            && (this.getFundShareClass() == null ? other.getFundShareClass() == null : this.getFundShareClass().equals(other.getFundShareClass()))
            && (this.getFundPrincipalSecurity() == null ? other.getFundPrincipalSecurity() == null : this.getFundPrincipalSecurity().equals(other.getFundPrincipalSecurity()))
            && (this.getFundPredate() == null ? other.getFundPredate() == null : this.getFundPredate().equals(other.getFundPredate()))
            && (this.getIsupresult() == null ? other.getIsupresult() == null : this.getIsupresult().equals(other.getIsupresult()))
            && (this.getFundUserName() == null ? other.getFundUserName() == null : this.getFundUserName().equals(other.getFundUserName()))
            && (this.getFundWeight() == null ? other.getFundWeight() == null : this.getFundWeight().equals(other.getFundWeight()))
            && (this.getFundTitle() == null ? other.getFundTitle() == null : this.getFundTitle().equals(other.getFundTitle()))
            && (this.getFundProfitType() == null ? other.getFundProfitType() == null : this.getFundProfitType().equals(other.getFundProfitType()))
            && (this.getFundCreateProfit() == null ? other.getFundCreateProfit() == null : this.getFundCreateProfit().equals(other.getFundCreateProfit()))
            && (this.getFundSixmonthsProfit() == null ? other.getFundSixmonthsProfit() == null : this.getFundSixmonthsProfit().equals(other.getFundSixmonthsProfit()))
            && (this.getFundThreemonthsProfit() == null ? other.getFundThreemonthsProfit() == null : this.getFundThreemonthsProfit().equals(other.getFundThreemonthsProfit()))
            && (this.getFundTwoyearsProfit() == null ? other.getFundTwoyearsProfit() == null : this.getFundTwoyearsProfit().equals(other.getFundTwoyearsProfit()))
            && (this.getFundThreeyearsProfit() == null ? other.getFundThreeyearsProfit() == null : this.getFundThreeyearsProfit().equals(other.getFundThreeyearsProfit()))
            && (this.getFundSinceyearsProfit() == null ? other.getFundSinceyearsProfit() == null : this.getFundSinceyearsProfit().equals(other.getFundSinceyearsProfit()))
            && (this.getFundOnemonthsProfit() == null ? other.getFundOnemonthsProfit() == null : this.getFundOnemonthsProfit().equals(other.getFundOnemonthsProfit()))
            && (this.getFundTags() == null ? other.getFundTags() == null : this.getFundTags().equals(other.getFundTags()))
            && (this.getFundAnnexFileId() == null ? other.getFundAnnexFileId() == null : this.getFundAnnexFileId().equals(other.getFundAnnexFileId()))
            && (this.getFundRecommendText() == null ? other.getFundRecommendText() == null : this.getFundRecommendText().equals(other.getFundRecommendText()))
            && (this.getFundQuasicloseTime() == null ? other.getFundQuasicloseTime() == null : this.getFundQuasicloseTime().equals(other.getFundQuasicloseTime()))
            && (this.getFundSerialId() == null ? other.getFundSerialId() == null : this.getFundSerialId().equals(other.getFundSerialId()))
            && (this.getFundNotype() == null ? other.getFundNotype() == null : this.getFundNotype().equals(other.getFundNotype()))
            && (this.getIsreport() == null ? other.getIsreport() == null : this.getIsreport().equals(other.getIsreport()))
            && (this.getIsfdsub() == null ? other.getIsfdsub() == null : this.getIsfdsub().equals(other.getIsfdsub()))
            && (this.getHisBatchId() == null ? other.getHisBatchId() == null : this.getHisBatchId().equals(other.getHisBatchId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFundId() == null) ? 0 : getFundId().hashCode());
        result = prime * result + ((getLastBatchId() == null) ? 0 : getLastBatchId().hashCode());
        result = prime * result + ((getFundName() == null) ? 0 : getFundName().hashCode());
        result = prime * result + ((getFundPinyinName() == null) ? 0 : getFundPinyinName().hashCode());
        result = prime * result + ((getFundPinyinSimplename() == null) ? 0 : getFundPinyinSimplename().hashCode());
        result = prime * result + ((getFundSimpleName() == null) ? 0 : getFundSimpleName().hashCode());
        result = prime * result + ((getFundCreatetime() == null) ? 0 : getFundCreatetime().hashCode());
        result = prime * result + ((getFundOpentime() == null) ? 0 : getFundOpentime().hashCode());
        result = prime * result + ((getFundType() == null) ? 0 : getFundType().hashCode());
        result = prime * result + ((getFundNo() == null) ? 0 : getFundNo().hashCode());
        result = prime * result + ((getFundStructure() == null) ? 0 : getFundStructure().hashCode());
        result = prime * result + ((getFundStatus() == null) ? 0 : getFundStatus().hashCode());
        result = prime * result + ((getFundNet() == null) ? 0 : getFundNet().hashCode());
        result = prime * result + ((getFundNetdate() == null) ? 0 : getFundNetdate().hashCode());
        result = prime * result + ((getFundUpnet() == null) ? 0 : getFundUpnet().hashCode());
        result = prime * result + ((getFundFileId() == null) ? 0 : getFundFileId().hashCode());
        result = prime * result + ((getFundInvestNav() == null) ? 0 : getFundInvestNav().hashCode());
        result = prime * result + ((getFundAddNav() == null) ? 0 : getFundAddNav().hashCode());
        result = prime * result + ((getFundSubscriptionNav() == null) ? 0 : getFundSubscriptionNav().hashCode());
        result = prime * result + ((getFundManagerNav() == null) ? 0 : getFundManagerNav().hashCode());
        result = prime * result + ((getFundRedeemNav() == null) ? 0 : getFundRedeemNav().hashCode());
        result = prime * result + ((getFundGrade() == null) ? 0 : getFundGrade().hashCode());
        result = prime * result + ((getFundFrom() == null) ? 0 : getFundFrom().hashCode());
        result = prime * result + ((getCreatDate() == null) ? 0 : getCreatDate().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getModifyDate() == null) ? 0 : getModifyDate().hashCode());
        result = prime * result + ((getModifier() == null) ? 0 : getModifier().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getPvNum() == null) ? 0 : getPvNum().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result + ((getFundLogoFileId() == null) ? 0 : getFundLogoFileId().hashCode());
        result = prime * result + ((getFundYearsProfit() == null) ? 0 : getFundYearsProfit().hashCode());
        result = prime * result + ((getOptionalNum() == null) ? 0 : getOptionalNum().hashCode());
        result = prime * result + ((getFundClosetime() == null) ? 0 : getFundClosetime().hashCode());
        result = prime * result + ((getFundInvestmentObject() == null) ? 0 : getFundInvestmentObject().hashCode());
        result = prime * result + ((getFundInvestmentStrategy() == null) ? 0 : getFundInvestmentStrategy().hashCode());
        result = prime * result + ((getFundTrustCompany() == null) ? 0 : getFundTrustCompany().hashCode());
        result = prime * result + ((getFundBank() == null) ? 0 : getFundBank().hashCode());
        result = prime * result + ((getFundShare() == null) ? 0 : getFundShare().hashCode());
        result = prime * result + ((getFundAssets() == null) ? 0 : getFundAssets().hashCode());
        result = prime * result + ((getFundRun() == null) ? 0 : getFundRun().hashCode());
        result = prime * result + ((getFundIdea() == null) ? 0 : getFundIdea().hashCode());
        result = prime * result + ((getFundAccountFrom() == null) ? 0 : getFundAccountFrom().hashCode());
        result = prime * result + ((getFundShareClass() == null) ? 0 : getFundShareClass().hashCode());
        result = prime * result + ((getFundPrincipalSecurity() == null) ? 0 : getFundPrincipalSecurity().hashCode());
        result = prime * result + ((getFundPredate() == null) ? 0 : getFundPredate().hashCode());
        result = prime * result + ((getIsupresult() == null) ? 0 : getIsupresult().hashCode());
        result = prime * result + ((getFundUserName() == null) ? 0 : getFundUserName().hashCode());
        result = prime * result + ((getFundWeight() == null) ? 0 : getFundWeight().hashCode());
        result = prime * result + ((getFundTitle() == null) ? 0 : getFundTitle().hashCode());
        result = prime * result + ((getFundProfitType() == null) ? 0 : getFundProfitType().hashCode());
        result = prime * result + ((getFundCreateProfit() == null) ? 0 : getFundCreateProfit().hashCode());
        result = prime * result + ((getFundSixmonthsProfit() == null) ? 0 : getFundSixmonthsProfit().hashCode());
        result = prime * result + ((getFundThreemonthsProfit() == null) ? 0 : getFundThreemonthsProfit().hashCode());
        result = prime * result + ((getFundTwoyearsProfit() == null) ? 0 : getFundTwoyearsProfit().hashCode());
        result = prime * result + ((getFundThreeyearsProfit() == null) ? 0 : getFundThreeyearsProfit().hashCode());
        result = prime * result + ((getFundSinceyearsProfit() == null) ? 0 : getFundSinceyearsProfit().hashCode());
        result = prime * result + ((getFundOnemonthsProfit() == null) ? 0 : getFundOnemonthsProfit().hashCode());
        result = prime * result + ((getFundTags() == null) ? 0 : getFundTags().hashCode());
        result = prime * result + ((getFundAnnexFileId() == null) ? 0 : getFundAnnexFileId().hashCode());
        result = prime * result + ((getFundRecommendText() == null) ? 0 : getFundRecommendText().hashCode());
        result = prime * result + ((getFundQuasicloseTime() == null) ? 0 : getFundQuasicloseTime().hashCode());
        result = prime * result + ((getFundSerialId() == null) ? 0 : getFundSerialId().hashCode());
        result = prime * result + ((getFundNotype() == null) ? 0 : getFundNotype().hashCode());
        result = prime * result + ((getIsreport() == null) ? 0 : getIsreport().hashCode());
        result = prime * result + ((getIsfdsub() == null) ? 0 : getIsfdsub().hashCode());
        result = prime * result + ((getHisBatchId() == null) ? 0 : getHisBatchId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fundId=").append(fundId);
        sb.append(", lastBatchId=").append(lastBatchId);
        sb.append(", fundName=").append(fundName);
        sb.append(", fundPinyinName=").append(fundPinyinName);
        sb.append(", fundPinyinSimplename=").append(fundPinyinSimplename);
        sb.append(", fundSimpleName=").append(fundSimpleName);
        sb.append(", fundCreatetime=").append(fundCreatetime);
        sb.append(", fundOpentime=").append(fundOpentime);
        sb.append(", fundType=").append(fundType);
        sb.append(", fundNo=").append(fundNo);
        sb.append(", fundStructure=").append(fundStructure);
        sb.append(", fundStatus=").append(fundStatus);
        sb.append(", fundNet=").append(fundNet);
        sb.append(", fundNetdate=").append(fundNetdate);
        sb.append(", fundUpnet=").append(fundUpnet);
        sb.append(", fundFileId=").append(fundFileId);
        sb.append(", fundInvestNav=").append(fundInvestNav);
        sb.append(", fundAddNav=").append(fundAddNav);
        sb.append(", fundSubscriptionNav=").append(fundSubscriptionNav);
        sb.append(", fundManagerNav=").append(fundManagerNav);
        sb.append(", fundRedeemNav=").append(fundRedeemNav);
        sb.append(", fundGrade=").append(fundGrade);
        sb.append(", fundFrom=").append(fundFrom);
        sb.append(", creatDate=").append(creatDate);
        sb.append(", creator=").append(creator);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", modifier=").append(modifier);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", pvNum=").append(pvNum);
        sb.append(", weight=").append(weight);
        sb.append(", fundLogoFileId=").append(fundLogoFileId);
        sb.append(", fundYearsProfit=").append(fundYearsProfit);
        sb.append(", optionalNum=").append(optionalNum);
        sb.append(", fundClosetime=").append(fundClosetime);
        sb.append(", fundInvestmentObject=").append(fundInvestmentObject);
        sb.append(", fundInvestmentStrategy=").append(fundInvestmentStrategy);
        sb.append(", fundTrustCompany=").append(fundTrustCompany);
        sb.append(", fundBank=").append(fundBank);
        sb.append(", fundShare=").append(fundShare);
        sb.append(", fundAssets=").append(fundAssets);
        sb.append(", fundRun=").append(fundRun);
        sb.append(", fundIdea=").append(fundIdea);
        sb.append(", fundAccountFrom=").append(fundAccountFrom);
        sb.append(", fundShareClass=").append(fundShareClass);
        sb.append(", fundPrincipalSecurity=").append(fundPrincipalSecurity);
        sb.append(", fundPredate=").append(fundPredate);
        sb.append(", isupresult=").append(isupresult);
        sb.append(", fundUserName=").append(fundUserName);
        sb.append(", fundWeight=").append(fundWeight);
        sb.append(", fundTitle=").append(fundTitle);
        sb.append(", fundProfitType=").append(fundProfitType);
        sb.append(", fundCreateProfit=").append(fundCreateProfit);
        sb.append(", fundSixmonthsProfit=").append(fundSixmonthsProfit);
        sb.append(", fundThreemonthsProfit=").append(fundThreemonthsProfit);
        sb.append(", fundTwoyearsProfit=").append(fundTwoyearsProfit);
        sb.append(", fundThreeyearsProfit=").append(fundThreeyearsProfit);
        sb.append(", fundSinceyearsProfit=").append(fundSinceyearsProfit);
        sb.append(", fundOnemonthsProfit=").append(fundOnemonthsProfit);
        sb.append(", fundTags=").append(fundTags);
        sb.append(", fundAnnexFileId=").append(fundAnnexFileId);
        sb.append(", fundRecommendText=").append(fundRecommendText);
        sb.append(", fundQuasicloseTime=").append(fundQuasicloseTime);
        sb.append(", fundSerialId=").append(fundSerialId);
        sb.append(", fundNotype=").append(fundNotype);
        sb.append(", isreport=").append(isreport);
        sb.append(", isfdsub=").append(isfdsub);
        sb.append(", hisBatchId=").append(hisBatchId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}