package com.lji.local.spring.ism.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class IsmFundMonthReturnTemp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundmonthreturn_temp.fundmonthreturn_id
     *
     * @mbggenerated
     */
    private String fundmonthreturnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundmonthreturn_temp.fund_temp_id
     *
     * @mbggenerated
     */
    private String fundTempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundmonthreturn_temp.month_return_num
     *
     * @mbggenerated
     */
    private BigDecimal monthReturnNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundmonthreturn_temp.months
     *
     * @mbggenerated
     */
    private Date months;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundmonthreturn_temp.creat_date
     *
     * @mbggenerated
     */
    private Date creatDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundmonthreturn_temp.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundmonthreturn_temp.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fundmonthreturn_temp.MODIFIER
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundmonthreturn_temp.fundmonthreturn_id
     *
     * @return the value of ism_fundmonthreturn_temp.fundmonthreturn_id
     *
     * @mbggenerated
     */
    public String getFundmonthreturnId() {
        return fundmonthreturnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundmonthreturn_temp.fundmonthreturn_id
     *
     * @param fundmonthreturnId the value for ism_fundmonthreturn_temp.fundmonthreturn_id
     *
     * @mbggenerated
     */
    public void setFundmonthreturnId(String fundmonthreturnId) {
        this.fundmonthreturnId = fundmonthreturnId == null ? null : fundmonthreturnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundmonthreturn_temp.fund_temp_id
     *
     * @return the value of ism_fundmonthreturn_temp.fund_temp_id
     *
     * @mbggenerated
     */
    public String getFundTempId() {
        return fundTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundmonthreturn_temp.fund_temp_id
     *
     * @param fundTempId the value for ism_fundmonthreturn_temp.fund_temp_id
     *
     * @mbggenerated
     */
    public void setFundTempId(String fundTempId) {
        this.fundTempId = fundTempId == null ? null : fundTempId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundmonthreturn_temp.month_return_num
     *
     * @return the value of ism_fundmonthreturn_temp.month_return_num
     *
     * @mbggenerated
     */
    public BigDecimal getMonthReturnNum() {
        return monthReturnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundmonthreturn_temp.month_return_num
     *
     * @param monthReturnNum the value for ism_fundmonthreturn_temp.month_return_num
     *
     * @mbggenerated
     */
    public void setMonthReturnNum(BigDecimal monthReturnNum) {
        this.monthReturnNum = monthReturnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundmonthreturn_temp.months
     *
     * @return the value of ism_fundmonthreturn_temp.months
     *
     * @mbggenerated
     */
    public Date getMonths() {
        return months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundmonthreturn_temp.months
     *
     * @param months the value for ism_fundmonthreturn_temp.months
     *
     * @mbggenerated
     */
    public void setMonths(Date months) {
        this.months = months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundmonthreturn_temp.creat_date
     *
     * @return the value of ism_fundmonthreturn_temp.creat_date
     *
     * @mbggenerated
     */
    public Date getCreatDate() {
        return creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundmonthreturn_temp.creat_date
     *
     * @param creatDate the value for ism_fundmonthreturn_temp.creat_date
     *
     * @mbggenerated
     */
    public void setCreatDate(Date creatDate) {
        this.creatDate = creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundmonthreturn_temp.creator
     *
     * @return the value of ism_fundmonthreturn_temp.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundmonthreturn_temp.creator
     *
     * @param creator the value for ism_fundmonthreturn_temp.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundmonthreturn_temp.modify_date
     *
     * @return the value of ism_fundmonthreturn_temp.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundmonthreturn_temp.modify_date
     *
     * @param modifyDate the value for ism_fundmonthreturn_temp.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fundmonthreturn_temp.MODIFIER
     *
     * @return the value of ism_fundmonthreturn_temp.MODIFIER
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fundmonthreturn_temp.MODIFIER
     *
     * @param modifier the value for ism_fundmonthreturn_temp.MODIFIER
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IsmFundMonthReturnTemp other = (IsmFundMonthReturnTemp) that;
        return (this.getFundmonthreturnId() == null ? other.getFundmonthreturnId() == null : this.getFundmonthreturnId().equals(other.getFundmonthreturnId()))
            && (this.getFundTempId() == null ? other.getFundTempId() == null : this.getFundTempId().equals(other.getFundTempId()))
            && (this.getMonthReturnNum() == null ? other.getMonthReturnNum() == null : this.getMonthReturnNum().equals(other.getMonthReturnNum()))
            && (this.getMonths() == null ? other.getMonths() == null : this.getMonths().equals(other.getMonths()))
            && (this.getCreatDate() == null ? other.getCreatDate() == null : this.getCreatDate().equals(other.getCreatDate()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getModifyDate() == null ? other.getModifyDate() == null : this.getModifyDate().equals(other.getModifyDate()))
            && (this.getModifier() == null ? other.getModifier() == null : this.getModifier().equals(other.getModifier()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFundmonthreturnId() == null) ? 0 : getFundmonthreturnId().hashCode());
        result = prime * result + ((getFundTempId() == null) ? 0 : getFundTempId().hashCode());
        result = prime * result + ((getMonthReturnNum() == null) ? 0 : getMonthReturnNum().hashCode());
        result = prime * result + ((getMonths() == null) ? 0 : getMonths().hashCode());
        result = prime * result + ((getCreatDate() == null) ? 0 : getCreatDate().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getModifyDate() == null) ? 0 : getModifyDate().hashCode());
        result = prime * result + ((getModifier() == null) ? 0 : getModifier().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fundmonthreturnId=").append(fundmonthreturnId);
        sb.append(", fundTempId=").append(fundTempId);
        sb.append(", monthReturnNum=").append(monthReturnNum);
        sb.append(", months=").append(months);
        sb.append(", creatDate=").append(creatDate);
        sb.append(", creator=").append(creator);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", modifier=").append(modifier);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}