package com.lji.local.spring.ism.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class IsmFundNet implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_net_log.fund_flow_id
     *
     * @mbggenerated
     */
    private String fundFlowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_net_log.fund_id
     *
     * @mbggenerated
     */
    private String fundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_net_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_net_log.fund_net
     *
     * @mbggenerated
     */
    private BigDecimal fundNet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_net_log.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_net_log.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_net_log.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_net_log.fund_source
     *
     * @mbggenerated
     */
    private Integer fundSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_fund_net_log.fund_upnet
     *
     * @mbggenerated
     */
    private BigDecimal fundUpnet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_fund_net_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_net_log.fund_flow_id
     *
     * @return the value of ism_fund_net_log.fund_flow_id
     *
     * @mbggenerated
     */
    public String getFundFlowId() {
        return fundFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_net_log.fund_flow_id
     *
     * @param fundFlowId the value for ism_fund_net_log.fund_flow_id
     *
     * @mbggenerated
     */
    public void setFundFlowId(String fundFlowId) {
        this.fundFlowId = fundFlowId == null ? null : fundFlowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_net_log.fund_id
     *
     * @return the value of ism_fund_net_log.fund_id
     *
     * @mbggenerated
     */
    public String getFundId() {
        return fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_net_log.fund_id
     *
     * @param fundId the value for ism_fund_net_log.fund_id
     *
     * @mbggenerated
     */
    public void setFundId(String fundId) {
        this.fundId = fundId == null ? null : fundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_net_log.create_time
     *
     * @return the value of ism_fund_net_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_net_log.create_time
     *
     * @param createTime the value for ism_fund_net_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_net_log.fund_net
     *
     * @return the value of ism_fund_net_log.fund_net
     *
     * @mbggenerated
     */
    public BigDecimal getFundNet() {
        return fundNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_net_log.fund_net
     *
     * @param fundNet the value for ism_fund_net_log.fund_net
     *
     * @mbggenerated
     */
    public void setFundNet(BigDecimal fundNet) {
        this.fundNet = fundNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_net_log.creator
     *
     * @return the value of ism_fund_net_log.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_net_log.creator
     *
     * @param creator the value for ism_fund_net_log.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_net_log.modify_date
     *
     * @return the value of ism_fund_net_log.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_net_log.modify_date
     *
     * @param modifyDate the value for ism_fund_net_log.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_net_log.modifier
     *
     * @return the value of ism_fund_net_log.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_net_log.modifier
     *
     * @param modifier the value for ism_fund_net_log.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_net_log.fund_source
     *
     * @return the value of ism_fund_net_log.fund_source
     *
     * @mbggenerated
     */
    public Integer getFundSource() {
        return fundSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_net_log.fund_source
     *
     * @param fundSource the value for ism_fund_net_log.fund_source
     *
     * @mbggenerated
     */
    public void setFundSource(Integer fundSource) {
        this.fundSource = fundSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_fund_net_log.fund_upnet
     *
     * @return the value of ism_fund_net_log.fund_upnet
     *
     * @mbggenerated
     */
    public BigDecimal getFundUpnet() {
        return fundUpnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_fund_net_log.fund_upnet
     *
     * @param fundUpnet the value for ism_fund_net_log.fund_upnet
     *
     * @mbggenerated
     */
    public void setFundUpnet(BigDecimal fundUpnet) {
        this.fundUpnet = fundUpnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_net_log
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IsmFundNet other = (IsmFundNet) that;
        return (this.getFundFlowId() == null ? other.getFundFlowId() == null : this.getFundFlowId().equals(other.getFundFlowId()))
            && (this.getFundId() == null ? other.getFundId() == null : this.getFundId().equals(other.getFundId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getFundNet() == null ? other.getFundNet() == null : this.getFundNet().equals(other.getFundNet()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getModifyDate() == null ? other.getModifyDate() == null : this.getModifyDate().equals(other.getModifyDate()))
            && (this.getModifier() == null ? other.getModifier() == null : this.getModifier().equals(other.getModifier()))
            && (this.getFundSource() == null ? other.getFundSource() == null : this.getFundSource().equals(other.getFundSource()))
            && (this.getFundUpnet() == null ? other.getFundUpnet() == null : this.getFundUpnet().equals(other.getFundUpnet()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_net_log
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFundFlowId() == null) ? 0 : getFundFlowId().hashCode());
        result = prime * result + ((getFundId() == null) ? 0 : getFundId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getFundNet() == null) ? 0 : getFundNet().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getModifyDate() == null) ? 0 : getModifyDate().hashCode());
        result = prime * result + ((getModifier() == null) ? 0 : getModifier().hashCode());
        result = prime * result + ((getFundSource() == null) ? 0 : getFundSource().hashCode());
        result = prime * result + ((getFundUpnet() == null) ? 0 : getFundUpnet().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_net_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fundFlowId=").append(fundFlowId);
        sb.append(", fundId=").append(fundId);
        sb.append(", createTime=").append(createTime);
        sb.append(", fundNet=").append(fundNet);
        sb.append(", creator=").append(creator);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", modifier=").append(modifier);
        sb.append(", fundSource=").append(fundSource);
        sb.append(", fundUpnet=").append(fundUpnet);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}