package com.lji.local.spring.ism.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IsmQuotationCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    public IsmQuotationCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuotationIdIsNull() {
            addCriterion("quotation_id is null");
            return (Criteria) this;
        }

        public Criteria andQuotationIdIsNotNull() {
            addCriterion("quotation_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuotationIdEqualTo(String value) {
            addCriterion("quotation_id =", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdNotEqualTo(String value) {
            addCriterion("quotation_id <>", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdGreaterThan(String value) {
            addCriterion("quotation_id >", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdGreaterThanOrEqualTo(String value) {
            addCriterion("quotation_id >=", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdLessThan(String value) {
            addCriterion("quotation_id <", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdLessThanOrEqualTo(String value) {
            addCriterion("quotation_id <=", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdLike(String value) {
            addCriterion("quotation_id like", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdNotLike(String value) {
            addCriterion("quotation_id not like", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdIn(List<String> values) {
            addCriterion("quotation_id in", values, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdNotIn(List<String> values) {
            addCriterion("quotation_id not in", values, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdBetween(String value1, String value2) {
            addCriterion("quotation_id between", value1, value2, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdNotBetween(String value1, String value2) {
            addCriterion("quotation_id not between", value1, value2, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationValueIsNull() {
            addCriterion("quotation_value is null");
            return (Criteria) this;
        }

        public Criteria andQuotationValueIsNotNull() {
            addCriterion("quotation_value is not null");
            return (Criteria) this;
        }

        public Criteria andQuotationValueEqualTo(String value) {
            addCriterion("quotation_value =", value, "quotationValue");
            return (Criteria) this;
        }

        public Criteria andQuotationValueNotEqualTo(String value) {
            addCriterion("quotation_value <>", value, "quotationValue");
            return (Criteria) this;
        }

        public Criteria andQuotationValueGreaterThan(String value) {
            addCriterion("quotation_value >", value, "quotationValue");
            return (Criteria) this;
        }

        public Criteria andQuotationValueGreaterThanOrEqualTo(String value) {
            addCriterion("quotation_value >=", value, "quotationValue");
            return (Criteria) this;
        }

        public Criteria andQuotationValueLessThan(String value) {
            addCriterion("quotation_value <", value, "quotationValue");
            return (Criteria) this;
        }

        public Criteria andQuotationValueLessThanOrEqualTo(String value) {
            addCriterion("quotation_value <=", value, "quotationValue");
            return (Criteria) this;
        }

        public Criteria andQuotationValueLike(String value) {
            addCriterion("quotation_value like", value, "quotationValue");
            return (Criteria) this;
        }

        public Criteria andQuotationValueNotLike(String value) {
            addCriterion("quotation_value not like", value, "quotationValue");
            return (Criteria) this;
        }

        public Criteria andQuotationValueIn(List<String> values) {
            addCriterion("quotation_value in", values, "quotationValue");
            return (Criteria) this;
        }

        public Criteria andQuotationValueNotIn(List<String> values) {
            addCriterion("quotation_value not in", values, "quotationValue");
            return (Criteria) this;
        }

        public Criteria andQuotationValueBetween(String value1, String value2) {
            addCriterion("quotation_value between", value1, value2, "quotationValue");
            return (Criteria) this;
        }

        public Criteria andQuotationValueNotBetween(String value1, String value2) {
            addCriterion("quotation_value not between", value1, value2, "quotationValue");
            return (Criteria) this;
        }

        public Criteria andQuotationTypeIsNull() {
            addCriterion("quotation_type is null");
            return (Criteria) this;
        }

        public Criteria andQuotationTypeIsNotNull() {
            addCriterion("quotation_type is not null");
            return (Criteria) this;
        }

        public Criteria andQuotationTypeEqualTo(Integer value) {
            addCriterion("quotation_type =", value, "quotationType");
            return (Criteria) this;
        }

        public Criteria andQuotationTypeNotEqualTo(Integer value) {
            addCriterion("quotation_type <>", value, "quotationType");
            return (Criteria) this;
        }

        public Criteria andQuotationTypeGreaterThan(Integer value) {
            addCriterion("quotation_type >", value, "quotationType");
            return (Criteria) this;
        }

        public Criteria andQuotationTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("quotation_type >=", value, "quotationType");
            return (Criteria) this;
        }

        public Criteria andQuotationTypeLessThan(Integer value) {
            addCriterion("quotation_type <", value, "quotationType");
            return (Criteria) this;
        }

        public Criteria andQuotationTypeLessThanOrEqualTo(Integer value) {
            addCriterion("quotation_type <=", value, "quotationType");
            return (Criteria) this;
        }

        public Criteria andQuotationTypeIn(List<Integer> values) {
            addCriterion("quotation_type in", values, "quotationType");
            return (Criteria) this;
        }

        public Criteria andQuotationTypeNotIn(List<Integer> values) {
            addCriterion("quotation_type not in", values, "quotationType");
            return (Criteria) this;
        }

        public Criteria andQuotationTypeBetween(Integer value1, Integer value2) {
            addCriterion("quotation_type between", value1, value2, "quotationType");
            return (Criteria) this;
        }

        public Criteria andQuotationTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("quotation_type not between", value1, value2, "quotationType");
            return (Criteria) this;
        }

        public Criteria andCreatDateIsNull() {
            addCriterion("creat_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatDateIsNotNull() {
            addCriterion("creat_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatDateEqualTo(Date value) {
            addCriterion("creat_date =", value, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateNotEqualTo(Date value) {
            addCriterion("creat_date <>", value, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateGreaterThan(Date value) {
            addCriterion("creat_date >", value, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateGreaterThanOrEqualTo(Date value) {
            addCriterion("creat_date >=", value, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateLessThan(Date value) {
            addCriterion("creat_date <", value, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateLessThanOrEqualTo(Date value) {
            addCriterion("creat_date <=", value, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateIn(List<Date> values) {
            addCriterion("creat_date in", values, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateNotIn(List<Date> values) {
            addCriterion("creat_date not in", values, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateBetween(Date value1, Date value2) {
            addCriterion("creat_date between", value1, value2, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatDateNotBetween(Date value1, Date value2) {
            addCriterion("creat_date not between", value1, value2, "creatDate");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("modify_date is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("modify_date is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("modify_date =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("modify_date <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("modify_date >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_date >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("modify_date <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("modify_date <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("modify_date in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("modify_date not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("modify_date between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("modify_date not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("modifier like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("modifier not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("modifier not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andQuotationIdLikeInsensitive(String value) {
            addCriterion("upper(quotation_id) like", value.toUpperCase(), "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationValueLikeInsensitive(String value) {
            addCriterion("upper(quotation_value) like", value.toUpperCase(), "quotationValue");
            return (Criteria) this;
        }

        public Criteria andCreatorLikeInsensitive(String value) {
            addCriterion("upper(creator) like", value.toUpperCase(), "creator");
            return (Criteria) this;
        }

        public Criteria andModifierLikeInsensitive(String value) {
            addCriterion("upper(modifier) like", value.toUpperCase(), "modifier");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ism_quotation
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}