package com.lji.local.spring.dce.dao;

import com.lji.local.spring.dce.model.DceAchievements;
import com.lji.local.spring.dce.model.DceAchievementsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DceAchievementsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int countByExample(DceAchievementsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int deleteByExample(DceAchievementsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String achievementsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int insert(DceAchievements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int insertSelective(DceAchievements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    List<DceAchievements> selectByExampleWithRowbounds(DceAchievementsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    List<DceAchievements> selectByExample(DceAchievementsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    DceAchievements selectByPrimaryKey(String achievementsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DceAchievements record, @Param("example") DceAchievementsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DceAchievements record, @Param("example") DceAchievementsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DceAchievements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DceAchievements record);
}