package com.lji.local.spring.dce.dao;

import com.lji.local.spring.dce.model.DceFundMonthReturn;
import com.lji.local.spring.dce.model.DceFundMonthReturnCriteria;
import com.lji.local.spring.dce.model.DceFundMonthReturnKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DceFundMonthReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int countByExample(DceFundMonthReturnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int deleteByExample(DceFundMonthReturnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DceFundMonthReturnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int insert(DceFundMonthReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int insertSelective(DceFundMonthReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    List<DceFundMonthReturn> selectByExampleWithRowbounds(DceFundMonthReturnCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    List<DceFundMonthReturn> selectByExample(DceFundMonthReturnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    DceFundMonthReturn selectByPrimaryKey(DceFundMonthReturnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DceFundMonthReturn record, @Param("example") DceFundMonthReturnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DceFundMonthReturn record, @Param("example") DceFundMonthReturnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DceFundMonthReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DceFundMonthReturn record);
}