package com.lji.local.spring.dce.dao;

import com.lji.local.spring.dce.model.DceFundDailyRor;
import com.lji.local.spring.dce.model.DceFundDailyRorCriteria;
import com.lji.local.spring.dce.model.DceFundDailyRorKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DceFundDailyRorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_daily_ror
     *
     * @mbggenerated
     */
    int countByExample(DceFundDailyRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_daily_ror
     *
     * @mbggenerated
     */
    int deleteByExample(DceFundDailyRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_daily_ror
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DceFundDailyRorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_daily_ror
     *
     * @mbggenerated
     */
    int insert(DceFundDailyRor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_daily_ror
     *
     * @mbggenerated
     */
    int insertSelective(DceFundDailyRor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_daily_ror
     *
     * @mbggenerated
     */
    List<DceFundDailyRor> selectByExampleWithRowbounds(DceFundDailyRorCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_daily_ror
     *
     * @mbggenerated
     */
    List<DceFundDailyRor> selectByExample(DceFundDailyRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_daily_ror
     *
     * @mbggenerated
     */
    DceFundDailyRor selectByPrimaryKey(DceFundDailyRorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_daily_ror
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DceFundDailyRor record, @Param("example") DceFundDailyRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_daily_ror
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DceFundDailyRor record, @Param("example") DceFundDailyRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_daily_ror
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DceFundDailyRor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_daily_ror
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DceFundDailyRor record);
}