package com.lji.local.spring.dce.dao;

import com.lji.local.spring.dce.model.DceFund;
import com.lji.local.spring.dce.model.DceFundCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DceFundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int countByExample(DceFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int deleteByExample(DceFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fundTempId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int insert(DceFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int insertSelective(DceFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    List<DceFund> selectByExampleWithRowbounds(DceFundCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    List<DceFund> selectByExample(DceFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    DceFund selectByPrimaryKey(String fundTempId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DceFund record, @Param("example") DceFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DceFund record, @Param("example") DceFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DceFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DceFund record);
}