package com.lji.local.spring.dce.dao;

import com.lji.local.spring.dce.model.DceFundWeekRor;
import com.lji.local.spring.dce.model.DceFundWeekRorCriteria;
import com.lji.local.spring.dce.model.DceFundWeekRorKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DceFundWeekRorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_week_ror
     *
     * @mbggenerated
     */
    int countByExample(DceFundWeekRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_week_ror
     *
     * @mbggenerated
     */
    int deleteByExample(DceFundWeekRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_week_ror
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DceFundWeekRorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_week_ror
     *
     * @mbggenerated
     */
    int insert(DceFundWeekRor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_week_ror
     *
     * @mbggenerated
     */
    int insertSelective(DceFundWeekRor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_week_ror
     *
     * @mbggenerated
     */
    List<DceFundWeekRor> selectByExampleWithRowbounds(DceFundWeekRorCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_week_ror
     *
     * @mbggenerated
     */
    List<DceFundWeekRor> selectByExample(DceFundWeekRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_week_ror
     *
     * @mbggenerated
     */
    DceFundWeekRor selectByPrimaryKey(DceFundWeekRorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_week_ror
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DceFundWeekRor record, @Param("example") DceFundWeekRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_week_ror
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DceFundWeekRor record, @Param("example") DceFundWeekRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_week_ror
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DceFundWeekRor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_week_ror
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DceFundWeekRor record);
}