package com.lji.local.spring.dce.dao;

import com.lji.local.spring.dce.model.DceFundMonthRor;
import com.lji.local.spring.dce.model.DceFundMonthRorCriteria;
import com.lji.local.spring.dce.model.DceFundMonthRorKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DceFundMonthRorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    int countByExample(DceFundMonthRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    int deleteByExample(DceFundMonthRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DceFundMonthRorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    int insert(DceFundMonthRor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    int insertSelective(DceFundMonthRor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    List<DceFundMonthRor> selectByExampleWithRowbounds(DceFundMonthRorCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    List<DceFundMonthRor> selectByExample(DceFundMonthRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    DceFundMonthRor selectByPrimaryKey(DceFundMonthRorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DceFundMonthRor record, @Param("example") DceFundMonthRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DceFundMonthRor record, @Param("example") DceFundMonthRorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DceFundMonthRor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_monthly_ror
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DceFundMonthRor record);
}