package com.lji.local.spring.dce.dao;

import com.lji.local.spring.dce.model.DceQuotation;
import com.lji.local.spring.dce.model.DceQuotationCriteria;
import com.lji.local.spring.dce.model.DceQuotationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DceQuotationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int countByExample(DceQuotationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int deleteByExample(DceQuotationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DceQuotationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int insert(DceQuotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int insertSelective(DceQuotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    List<DceQuotation> selectByExampleWithRowbounds(DceQuotationCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    List<DceQuotation> selectByExample(DceQuotationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    DceQuotation selectByPrimaryKey(DceQuotationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DceQuotation record, @Param("example") DceQuotationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DceQuotation record, @Param("example") DceQuotationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DceQuotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DceQuotation record);
}