package com.lji.local.spring.ism.dao;

import com.lji.local.spring.ism.model.IsmAchievementsTemp;
import com.lji.local.spring.ism.model.IsmAchievementsTempCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IsmAchievementsTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int countByExample(IsmAchievementsTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int deleteByExample(IsmAchievementsTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String achievementsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int insert(IsmAchievementsTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int insertSelective(IsmAchievementsTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    List<IsmAchievementsTemp> selectByExampleWithRowbounds(IsmAchievementsTempCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    List<IsmAchievementsTemp> selectByExample(IsmAchievementsTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    IsmAchievementsTemp selectByPrimaryKey(String achievementsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IsmAchievementsTemp record, @Param("example") IsmAchievementsTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IsmAchievementsTemp record, @Param("example") IsmAchievementsTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IsmAchievementsTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IsmAchievementsTemp record);
}