package com.lji.local.spring.ism.dao;

import com.lji.local.spring.ism.model.IsmAchievements;
import com.lji.local.spring.ism.model.IsmAchievementsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IsmAchievementsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements
     *
     * @mbggenerated
     */
    int countByExample(IsmAchievementsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements
     *
     * @mbggenerated
     */
    int deleteByExample(IsmAchievementsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String achievementsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements
     *
     * @mbggenerated
     */
    int insert(IsmAchievements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements
     *
     * @mbggenerated
     */
    int insertSelective(IsmAchievements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements
     *
     * @mbggenerated
     */
    List<IsmAchievements> selectByExampleWithRowbounds(IsmAchievementsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements
     *
     * @mbggenerated
     */
    List<IsmAchievements> selectByExample(IsmAchievementsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements
     *
     * @mbggenerated
     */
    IsmAchievements selectByPrimaryKey(String achievementsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IsmAchievements record, @Param("example") IsmAchievementsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IsmAchievements record, @Param("example") IsmAchievementsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IsmAchievements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_achievements
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IsmAchievements record);
}