package com.lji.local.spring.ism.dao;

import com.lji.local.spring.ism.model.IsmFund;
import com.lji.local.spring.ism.model.IsmFundCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IsmFundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    int countByExample(IsmFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    int deleteByExample(IsmFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fundId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    int insert(IsmFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    int insertSelective(IsmFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    List<IsmFund> selectByExampleWithBLOBsWithRowbounds(IsmFundCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    List<IsmFund> selectByExampleWithBLOBs(IsmFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    List<IsmFund> selectByExampleWithRowbounds(IsmFundCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    List<IsmFund> selectByExample(IsmFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    IsmFund selectByPrimaryKey(String fundId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IsmFund record, @Param("example") IsmFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") IsmFund record, @Param("example") IsmFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IsmFund record, @Param("example") IsmFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IsmFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(IsmFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IsmFund record);
}