package com.lji.local.spring.ism.dao;

import com.lji.local.spring.ism.model.IsmFundMonthReturn;
import com.lji.local.spring.ism.model.IsmFundMonthReturnCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IsmFundMonthReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn
     *
     * @mbggenerated
     */
    int countByExample(IsmFundMonthReturnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn
     *
     * @mbggenerated
     */
    int deleteByExample(IsmFundMonthReturnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fundReturnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn
     *
     * @mbggenerated
     */
    int insert(IsmFundMonthReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn
     *
     * @mbggenerated
     */
    int insertSelective(IsmFundMonthReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn
     *
     * @mbggenerated
     */
    List<IsmFundMonthReturn> selectByExampleWithRowbounds(IsmFundMonthReturnCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn
     *
     * @mbggenerated
     */
    List<IsmFundMonthReturn> selectByExample(IsmFundMonthReturnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn
     *
     * @mbggenerated
     */
    IsmFundMonthReturn selectByPrimaryKey(String fundReturnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IsmFundMonthReturn record, @Param("example") IsmFundMonthReturnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IsmFundMonthReturn record, @Param("example") IsmFundMonthReturnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IsmFundMonthReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IsmFundMonthReturn record);
}