package com.lji.local.spring.ism.dao;

import com.lji.local.spring.ism.model.IsmFundTemp;
import com.lji.local.spring.ism.model.IsmFundTempCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IsmFundTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int countByExample(IsmFundTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int deleteByExample(IsmFundTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fundTempId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int insert(IsmFundTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int insertSelective(IsmFundTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    List<IsmFundTemp> selectByExampleWithRowbounds(IsmFundTempCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    List<IsmFundTemp> selectByExample(IsmFundTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    IsmFundTemp selectByPrimaryKey(String fundTempId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IsmFundTemp record, @Param("example") IsmFundTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IsmFundTemp record, @Param("example") IsmFundTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IsmFundTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fund_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IsmFundTemp record);
}