package com.lji.local.spring.ism.dao;

import com.lji.local.spring.ism.model.IsmFundMonthReturnTemp;
import com.lji.local.spring.ism.model.IsmFundMonthReturnTempCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IsmFundMonthReturnTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int countByExample(IsmFundMonthReturnTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int deleteByExample(IsmFundMonthReturnTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fundmonthreturnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int insert(IsmFundMonthReturnTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int insertSelective(IsmFundMonthReturnTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    List<IsmFundMonthReturnTemp> selectByExampleWithRowbounds(IsmFundMonthReturnTempCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    List<IsmFundMonthReturnTemp> selectByExample(IsmFundMonthReturnTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    IsmFundMonthReturnTemp selectByPrimaryKey(String fundmonthreturnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IsmFundMonthReturnTemp record, @Param("example") IsmFundMonthReturnTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IsmFundMonthReturnTemp record, @Param("example") IsmFundMonthReturnTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IsmFundMonthReturnTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundmonthreturn_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IsmFundMonthReturnTemp record);
}