package com.lji.local.spring.ism.dao;

import com.lji.local.spring.ism.model.IsmFundNetTemp;
import com.lji.local.spring.ism.model.IsmFundNetTempCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IsmFundNetTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    int countByExample(IsmFundNetTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    int deleteByExample(IsmFundNetTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fundnetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    int insert(IsmFundNetTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    int insertSelective(IsmFundNetTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    List<IsmFundNetTemp> selectByExampleWithRowbounds(IsmFundNetTempCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    List<IsmFundNetTemp> selectByExample(IsmFundNetTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    IsmFundNetTemp selectByPrimaryKey(String fundnetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IsmFundNetTemp record, @Param("example") IsmFundNetTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IsmFundNetTemp record, @Param("example") IsmFundNetTempCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IsmFundNetTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_fundnet_temp_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IsmFundNetTemp record);
}