package com.lji.local.spring.ism.dao;

import com.lji.local.spring.ism.model.IsmQuotation;
import com.lji.local.spring.ism.model.IsmQuotationCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IsmQuotationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int countByExample(IsmQuotationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int deleteByExample(IsmQuotationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String quotationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int insert(IsmQuotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int insertSelective(IsmQuotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    List<IsmQuotation> selectByExampleWithRowbounds(IsmQuotationCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    List<IsmQuotation> selectByExample(IsmQuotationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    IsmQuotation selectByPrimaryKey(String quotationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IsmQuotation record, @Param("example") IsmQuotationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IsmQuotation record, @Param("example") IsmQuotationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IsmQuotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_quotation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IsmQuotation record);
}